Techtonica/curriculum

- jquery/jquery.md
remove jquery slides temporarily jquery.md since they are not available yet. posting them on topic outline, without them existing could be confusing.
> remove jquery slides temporarily jquery.md

- runtime-complexity/runtime-complexity.md
I noticed that the Runtime Complexity Lecture Video Slides were in the apprenticeship schedule, but not in the curriculum, so I thought it would be helpful to add them.
> Add Runtime Complexity Lecture Video Slides 

- roles-in-tech/security.md
After reading roles-in-tech.md, I thought the purpose of this section of lessons is to help participants gain an understanding of different kinds of roles. However, we also need to make sure participants going into any kind of coding role understand basic security. I feel like it's out of scope of this pull request, but I'd like to suggest separating out an actual security module/lesson out from this "roles in tech" section. 
For now, I propose adding sections on descriptions of different kinds of roles, relevant annual conferences, and (the stub of) a list of interesting people to follow.
Corresponding card: https://github.com/Techtonica/curriculum/issues/94
> [#94] More info about security roles.

- testing-and-tdd/backend-testing.md
- testing-and-tdd/testing-and-tdd.md
I made some minor changes to the backend testing lesson 😉
There are still a couple of things that need to be done; I've pulled them out in a non-rendering comment block at the top of the file but here it is for ease of reading:
```
[//]: # (TODO)
[//]: # (  - Still need slides)
[//]: # (  - This hasn't really been proofed yet and I'm _real bad_ about typos <3)
[//]: # (  - we should move all the @falun owned repl.it links to techtonica)
[//]: # (  - the backend snapshots should start move off my elephantsql.com account)
[//]: # (    at some point I'll delete the database it's using which will break the) 
[//]: # (    sample; when we _do_ rehome the sample change the following links:)
[backend-i]: https://repl.it/@falun/BackendTesting-I
[backend-ii]: …
```
> Adds a backend testing lesson

- testing-and-tdd/integration-testing.md
This is an initial reaction commit. Not an "omg u must do this instead" commit. I'm not entirely convinced splitting hairs over unit vs integration testing is worthwhile. I 100% agree that backend testing and front end testing are different skills with different techniques. (front end is much more event-driven, backend is often more promise driven).
I'm hopeful that by disambiguating between _integration_ and _unit_ testing we provide a box
for students to put information in as their mental model refines.
LMK if you think it's worth continuing down this path in this PR, or if you'd prefer we don't make such a significant change!
> Reframe from "Backend" testing to "Integration" testing

- oauth/o-auth.md
Admittedly it didn't feel like there was a good place to put logout, since the instructions / pairing up work ends at verifying a fix to configuring for Google login. I figure since this is really the goal of the session, I moved the challenges bit to be after the working session, and in there included a challenge based on logout.
- Moved the challenge section to be after "Check your Understanding"
- Added an additional challenge to tie into the logout slide added for Auth0.
> Updating to include tie in to logout material on slides

- projects/eventonica-project.md
The biggest changes were that
- The Inquirer.js tutorial previously referenced was a dead link. There aren't _great_ alternatives out there but we made do
- There isn't an exact parallel to Sequel Pro for postgres so we approximated what the point of it was (I think) by instructing them to run a SELECT to view changes rather than watching an event log.
- The starter project got moved to my repo with a rewrite to be targeting postgres and using `node-postgres` instead of `mysql`.
> Update Eventonica project for postgres

- debugging/debugging.md
Add general tips in the lesson section of debugging.md file and also fixes some typo errors.
Issue Fixed: #814
> Add general tips to debugging lesson

- javascript/javascript-6-object-literals.md
Not super relevant, but the examples above us camelCase instead of PascalCase, so I figured I'd toss in an edit.
> Changes from pascal case to camel case

- javascript/javascript-7-oop.md
This is just fixing one issue addressed in #945. Currently it's sending the user to a spreadsheet when it should be going to the tut linked in the fix.
> Adjust faulty link

- javascript/javascript-7-oop.md
There was concern in #945 that there was ambiguity surrounding the class hierarchy of `Book` and `AudioBook`. I'm hoping this clears it up a bit.
> Addressed audiobook ambiguity

- express-js/express.md
I removed the video that I believe it's outdated and unnecessary for the Express js curriculum. I linked the "Intro video series on Express.js" directly to the playlist's first video. This playlist about the intro of express is enough, and the "Express.js Tutorial (Level 1)" is not necessary.
Related Issue: https://github.com/Techtonica/curriculum/issues/960
> Remove unnecessary and outdated Express JS video

- mobile-development/mobile-development.md
Adding Roadmap to the study path will help developers in their study by showing what they need to know about each platform.
> Add android and iOS devloper Roadmap

- learning-to-learn/learning-to-learn.md
This is an alternative link that Zarina recommended on Slack to replace the old link that leads to a down web-page.
> replace dead link 'growth mindset quiz' to a working alternative

- solving-coding-challenges/solving-coding-challenges.md
Was missing "\" before the * in 2*2. Added so text shows up correctly.
> Fix typo in challenge prompt

- data-structures/hash-tables.md
Removed notes about HashMap vs Hashtable
- AFAIK that terminology is _Java-specific_ 
- Map, Dict, Hash, etc are all exactly the same data structure this is just needlessly confusing
> remove hashmap/hashtable clarification

- github-collaboration/github-collaboration.md
The previous link was incorrect. Fixed the error and added the right link
> Fix link to Github Collaboration Study Material

- security/web-security.md
Issue no. #1133 
In the Web Security lesson, I found the **Further Reading/Practice** section to be suitable for sharing the Twilio HTTP headers article. So, I have added the relevant link under this section. If there is some change that needs to be made please let me know. Thanks.
> Added Twilio HTTP headers article

- javascript/eslint.md
- linting/code-linting-eslint.md
Fixes #1201 Add outline for code liniting + eslint instructions
I've compiled a markdown `code-linting-eslint.md` with appropriate amount of instructions and resources for the topic. I wasn't able to figure out where to put it so i created `./linting` directory in root and here's my PR. Please have look and share your valuable feedback
> Closes issue #1201 outline for code liniting + eslint instructions 

- projects/eventonica/eventonica-part4-apis.md
Talked to Bill before sending. For eventonica-part-4, I tried to clarify the instructions, as I saw some apprentices struggling with listing all events retrieved by the ticketmaster API, and then adding the first event. Therefore, I tried to split the two objectives a little more cleanly and make the steps a little more explicit. Please check that I also understood the objectives correctly.
> Make instructions more explicit, remove ambiguity of 1 or 2 buttons

- dev-tools/command-line-advanced.md
- git/git-version-control.md
- node-js/node-lab-exercise-part-1.md
Closes Issue #1155 - Add homebrew to Advanced Command Line
1. Change dead link for Advanced command line, since it migrated from `../command-line/command-line-advanced.md` to `../dev-tools/command-line-advanced.md`.
2. Create a new section inside [Advanced Command Line](https://github.com/Techtonica/curriculum/blob/master/dev-tools/command-line-advanced.md) lesson about Homebrew which contains:
- what it is 
- how to install it
- guide practice to install an optional tool -> `wget`
- challenge to install other optional tool -> `tree`
3. Update installation for [git](https://github.com/Techtonica/curriculum/blame/master/git/git-version-control.md#L103) and [nvm](https://github.com/Techtonica/curriculum/blame/master/node-js/node-lab-exercise-part-1.md#L57) using Homebrew
> fix: add homebrew installation steps

- README.md
- deploying/deploying-to-heroku.md
- node-js/node-js.md
Should close #1363
- Changed deploying.md file name to deploying-to-heroku.md
- Removed one video link with label "Why use Node.js?" from node-js.md
- Added "A free Heroku account under prerequisites in deploying.md file
> Fix links in Deploying to Heroku outline

- README.md
- used https://github.com/ekalinin/github-markdown-toc to generate text
- this came up during a sponsor call where it was unclear if the program was only 14 weeks long
> add week-by-week TOC links to main README

- databases/sql.md
- projects/take-home-problems/backend.md
Addresses https://github.com/Techtonica/curriculum/issues/1204 by changing SQLite references and tooling to PostgreSQL.
In Addition:
https://github.com/Techtonica/curriculum/commit/387cf75ff4a8891168d33a709ac96091a3906956 updates the columns for the database to match the CSV pulled from the website in the instructions for backend.md.
https://github.com/Techtonica/curriculum/commit/5dc370e748dbf93dff9aab96568265f63dd8e6f7 fixes a typo in the reference to a previous step and corrects the link to the prereq lesson.
> Change SQLite references to PostgreSQL

- javascript/require-and-import-mini-lesson.md
This PR aims at bringing in a mini-lesson on `require` and `import`.
This closes #1221 
I followed the template as suggested, however, as it was hinted in the issue, I didn't include all sections. Mainly:
- I took out the materials section but I added a source section within additional materials
- I took our the Common Mistakes & Misconceptions since they are somewhat spread out into the chart
- I took out the independent practice
@vegetabill and @alodahl, I look forward to your comments! It was a hard topic to make a "mini" lesson. I hope it's not too much. Let me know!
---
Please note that I also attached the files for the guided practice code to this PR:
[require-and-import.zip](https://github.com/Techtonica/curriculum/files/5571026/require-and-import.zip)
> add: mini-lesson on require and import(1221)

- objectives/week-6-assessment.md
Currently it says that any topics covered after Monday February 10, 2020 will not be included. The equivalent date for the 2021 H1 cohort is Friday February 19, 2021.
> Update week 6 assessment topics date to 2021 ver

- .github/stale.yml
- Use different rules for issues vs pull requests
- Expand the stale window for issues to 180 days and exclude ones that have been "triaged" by the team and assigned to a milestone or project,  automatically without even needing "pinned" labels
- For issues, add messaging encouraging them to make their own pull request
Config docs: https://github.com/probot/stale#usage
> Improve stalebot config

- api/intro-to-http.md
telnet is deprecated and unsupported. Installing it on my machine yielded errors as shown in this thread
https://discussions.apple.com/thread/251160017
> propose to change requirement to install telnet

- databases/sql-1.md
I made a pull request to update the pre-reqs link to the database modeling part 1 lesson instead of the data models page that is currently listed.
> Update pre-requisites link

- api/intro-to-http.md
The "How the Internet Works" topic currently points to `requests-and-response.md`, but the file was since renamed to `how-the-internet-works.md` and moved to the `networking-computing` directory
> Update "Intro to HTTP" prerequisite link

- databases/data-modeling-2.md
Currently the NTU link redirects [to a 404 notice](https://personal.ntu.edu.sg/404.html) that NTU staff pages have been moved to a new URL, this PR updates it to the newer one
> Fix dead link in Data Modeling 2

- projects/eventonica/README.md
Currently the link for Part 8 points to `eventonica-part8-api-testind.md`, this PR fixes "testind" to "testing"
> Fix typo in Eventonica README for Part 8

- projects/eventonica/eventonica-part6-postgres.md
The typo in "EventRecomender" likely let it slide-by while renaming EventRecommender to Eventonica.
> Fix "EventRecomender" to "Eventonica"

- react-js/react-part4-full-apps.md
Duplicated Todo component in App.js after it has already been imported from Todo.js and will generate an error when attempting to declare it again. Removing it from App.js resolves the error. The Todo app may not render without refreshing the chrome tab that the default App.js was rendered in ( probably due to cache ).
> Remove duplicate Todo component, + info in parens

- onboarding/asking-good-questions.md
I think the times are a bit inflated in this section.  
These seem more accurate:
- 30 minutes for Independent Practice  (was 40)
- 10 minutes to check for understanding (was 15)
> Time Updates

- web/accessibility.md
- web/accessibility/aria.md
addresses https://github.com/Techtonica/curriculum/issues/1377
This PR adds/updates the following
- Developer resource links
- Assistive technologies links
-  Addition to `set up screen reader` instruction part
> docs(a11y): Add dev resources + AT links

- projects/eventonica-react/eventonica-express-backend.md
- projects/eventonica-react/eventonica-react-ui-advanced.md
- projects/eventonica-react/starter-code/mockEvents.js
updating some of the tutorials after seeing people go through Eventonica last week:
- more detailed walkthrough for the getUsers endpoint - add information about the req.body, using postman, and naming
- I want to encourage people to use Postman, since it can make debugging easier, and is a good skill for API development 
- an example of `useReducer` where multiple fields are updated by one action
- I feel like complex updating of state is one of the main benefits of `useReducer` -- the tutorial currently only shows one field at a time, so add another section about this
- make mock event IDs be strings, not int
- saw some issues where people were confused because the `input` sends back an ID as a string, but the event IDs are stored as numbers. I feel like this was an unnecessary hurdle, …
> Eventonica Updates

- projects/week-1-worksheet.md
Per [this comment](https://techtonicaorg.slack.com/archives/C4VAQ1VJ9/p1661212590971129) we noticed that members of the cohort were missing that they should be creating a `.zshrc` file. We want to add more explicit instructions to make sure they create the file.
There is [a bigger issue here pointed out by Stephen](https://techtonicaorg.slack.com/archives/C03H7Q16SJ0/p1660094695367829?thread_ts=1660074142.991999&cid=C03H7Q16SJ0) that we could rework this lesson to have a more explicit goal and success criteria. I do not agree/attempt to take on that scope. I'm just trying to do the bare minimum of adding a more explicit goal.
I hope others can expand from here: https://techtonicaorg.slack.com/archives/C03H7Q16SJ0/p1660094695367829?thread_ts=1660074142.991999&cid=C03H7Q16SJ0
> add specific instructions for creating zshrc

- projects/recipe-page/phase-1-html-prompt.md
Add code backticks around html tag references to ensure formatting. Without the backticks, the README has improper spacing formatting
Testing Notes: 
- ensure that [the new README ](https://github.com/Techtonica/curriculum/blob/f2fc842ee8f1a48825a1e255c7c6ed24da2afcb8/projects/recipe-page/phase-1-html-prompt.md)has proper formatting as shown in "After"
> Recipe page project - fix formatting bug

- web/js-dom-methods.md
Replaced a dead link to a tutorial on vanilla Javascript. Removed instructions only relevant to the tutorial.
> Replaced a dead link to a tutorial

- projects/react-game.md
Remove any references telling participants to start their project in a repl, such as codesandbox, codepen, replit, etc. Instead, encourage participants to start their project locally in order to test React and to utilize git version control to save all progress.
> Remove codesandbox references from react-game project and encourage git version control

- onboarding/learning-to-learn.md
Original problem found here: [Learning to Learn](https://github.com/Techtonica/curriculum/blob/main/onboarding/learning-to-learn.md)
"Existing quiz highlights a single learning style which is counter-intuitive to the debunked myth the participants learn in this lesson."
Previous Quiz: [Learning Style Quiz](http://www.educationplanner.org/students/self-assessments/learning-styles)
Updated Quiz: [Vark Questionnaire](https://vark-learn.com/the-vark-questionnaire/)
Under Supplemental Resources section, line 78 now contains the addition of the article [The Stubborn Myth of Learning Styles](https://www.educationnext.org/stubborn-myth-learning-styles-state-teacher-license-prep-materials-debunked-theory/) with the following summary: 
- "Despite the fact that learning styles are taught to …
> Fixing Issue 2063: Updating Learning to Learn lesson with new quiz and article

- onboarding/time-management.md
This PR introduces a new markdown file (`time-management.md`) to the onboarding folder, providing comprehensive content on time management for the organization. The document includes various sections aimed at helping Techtonica cohort members improve their productivity and effectively manage their time. The content used to create this document can be found ([here](https://docs.google.com/presentation/d/1VGlfYtWXQ8TEXsq4Bad0k2WZ-mK02hI3UwVXrfuUpPA/edit#slide=id.g1fdef94fa7_0_0)).
**1. Renaming:**  
Renamed `Time Management.md` to `time-management.md` to follow consistent naming conventions.
**2. Sections Added:**
- **Questions:** Added a list of key questions related to time management.
- **Prerequisites:** Defined prerequisites for time management concepts.
- **Common …
> Feedback Request: Preliminary Draft of Time Management Topic Outline #2091

- testing-and-tdd/compared-testing-frameworks.md
Description: 
for this issue, I have been assigned to update the comparing testing frameworks outline in the curriculum to: 
- clarify the differences between the various testing frameworks (e.g RTL, Vitest, Jest, Supertest, etc)
- provide examples/use cases for when to use each testing frameworks
- include necessary configuration or setup steps required for each testing framework to work properly within the project environment
Objective: 
- what is your PR doing and how does it provide a solution for your issue
- how does the code in your PR hope to accomplish
- what are your changes doing
> Issue #2112 - Creates comparing testing frameworks outline

- open-source/open-source.md
This pull request addresses [Issue #2158](https://github.com/Techtonica/curriculum/issues/2158) by updating the links in the **Supplemental Materials** section of the open-source curriculum. The updates standardize the naming conventions for the links, improving consistency and usability.
1. **Link Updates:**  
- Revised all links in the **Supplemental Materials** section to follow a consistent format:  
- Include the name of the list.   
- Display the creator/maintainer of the resource.  
- Indicate any filters applied by the specific link.  
2. **Consistency Improvements:**  
- Improved readability and navigability of the list by applying a uniform naming structure.  
3. **Post-PR #2153 Adjustments:**  
- Incorporated changes on top of the revised list structure introduced in PR #2153, …
> Resolving Issue #2158 - Standardizing Link Names in Supplemental Materials Section

- testing-and-tdd/integration-testing.md
This PR addresses issues related to missing reference links and some styling inconsistencies within the [Integration Testing](https://github.com/Techtonica/curriculum/blob/main/testing-and-tdd/integration-testing.md#specific-things-to-learn) file. 
- Fixed broken or missing links within the document.
- Standardized link formatting for consistency across sections.
- Fixed stylization throughout the file 
The objective of this PR is to resolve issues related to missing reference links and inconsistent styling throughout the `Integration Testing` file. 
@daaimah123, @mx-ruthie, @themagicianking  -- please review the link changes in this file.
> Fix formatting and link reference in Integration Testing file (#2111)

- react-js/react-part-4-component-hierarchies.md
This PR is for [issue 2231](https://github.com/Techtonica/curriculum/issues/2231). 
It is addressing the issue of fixing the broken/ outdated links. 
There were additional small edits for formatting. 
Here is a demonstration **before** the fix: 
Here is a demonstration **after** the fix:
> Update Broken Links on React Part 4 - Components & Hierarchies

- README.md
- electives/optimization/performance-optimization-react.md
- react-js/performance-optimization-react.md
Add a react performance optimization topic outline to the reactjs folder.
The following concepts are discussed and in depth interactive activities are provided: 
- React rendering lifecycle and performance implications
- Component memoization with `React.memo`, `useMemo`, and `useCallback`
- Code splitting and lazy loading techniques
- State management optimization strategies
- Virtual DOM and reconciliation process
- Profiling and measuring React performance
- Issue Number: #2284
- Explains the purpose of react performance optimization
- Considerate of target population: women and non-binary adults career continuing their learning journey into more advanced full stack software engineering concepts
- Introduce into Repo Table of contents "Week 7 Advanced JS & React" …
> [Issue 2283] Create performance-optimization-react.md

- machine-learning-systems-generative-ai-models/software-engineering-in-the-age-of-ai.md
This PR adds a new comprehensive topic outline focused on helping our program population understand and thrive in software engineering roles in the age of AI. The outline addresses concerns about AI-generated code and provides practical guidance on developing skills that complement rather than compete with AI capabilities.
- Added a new topic outline markdown file
- Created a structured curriculum with:
- Table of contents with hyperlinks
- "Specific Things to Learn" section highlighting essential skills
- Four detailed interactive activities with guided practice
- Common misconceptions section
- Starter code examples for activities
Issue Number: #2332
- Topic outline addresses the core questions from the issue (role of SWE with AI-generated code, career opportunities, …
> [Issue 2332] Create "Software Engineering in the Age of AI" topic outline

- algorithms/distributed-algorithms.md
This PR adds a comprehensive JavaScript implementation section to the Distributed Algorithms topic outline. It includes a detailed implementation of the Bully Algorithm for leader election in JavaScript, along with explanations of its relevance to the core learning objectives. The implementation demonstrates practical application of distributed systems concepts and provides career changers with concrete code examples they can analyze and run.
1. Added a new "Implementation" tab to the visual learning interface
2. Created a complete JavaScript implementation of the Bully Algorithm for leader election
3. Added explanations connecting the implementation to key distributed systems concepts
4. Added sections highlighting real-world applications and implementation challenges
5. Created explicit …
> [Issue 2277] Create "Distributed Algorithms" topic outline

- react-js/redux-state-management.md
This PR adds a comprehensive topic outline for Redux for State Management to the curriculum. It includes interactive code examples, visual representations of Redux concepts, and step-by-step activities to help participant understand Redux fundamentals and best practices.
- Added a complete Redux for State Management topic outline with table of contents
- Created 6 interactive activities covering Redux core concepts, implementation, and debugging
- Developed a visual representation of Redux DevTools workflow
- Included code examples for Redux, React-Redux, Redux Thunk, and Redux Toolkit
- Added common mistakes/misconceptions section to help learners avoid pitfalls
- Ensured all content is self-guided with clear time estimates for each activity
Issue Number: #2278
New Topic Outline in the …
> [Issue 2278] Create redux-state-management.md

- projects/blog-app/README.md
- projects/eventonica-updated/README.md
- projects/final-project/README.md
- projects/mern-pern-project.md
- projects/pern-contact-list-app.md
- projects/pern-game-app.md
- projects/pern-weather-app.md
- projects/week8GameREADME.md
- testing-and-tdd/compared-testing-frameworks.md
Audited FT program weeks 8+ google day docs & weeks 8+ project repo material to include vitest (and other testing framework) link references. Also added testing chart to compared testing file for visual learners.
- [Curriculum Google Drive Week 8+](https://drive.google.com/drive/u/0/folders/17fgBLGw-oTsAttr_hTSrStrtD72lc7YD)
- Game/Quiz App (Testing Introduced)
- Eventonica
- Endangered Animals
- 2 mini projects in 1 week! Contact List and Weather / Game Apps
- Blog App
- Final Project
- Visual testing framework comparison in testing comparison file
Issue Number: #2110
FT Program Documentation Update and Update to Project Topic Outlines
Ensure links work and redirect to appropriate testing outlines
> [Issue 2110] Integrate testing framework links into existing topic outlines

- algorithms/external-sorting-algorithms.md
This PR adds a comprehensive topic outline on External Sorting Algorithms to the curriculum. The outline provides both theoretical knowledge and practical implementation guidance. The content includes detailed explanations of various external sorting techniques, their applications, and self-guided activities for hands-on learning.
- Added a new topic outline on External Sorting Algorithms in the algorithms folder
- Created detailed explanations of external sorting concepts including External Merge Sort, Polyphase Merge Sort, Replacement Selection, and External Quicksort
- Developed four self-guided activities with complete instructions and starter code
- Included JavaScript implementations and examples throughout the content
- Added a section on common mistakes and misconceptions
- …
> [Issue 2275] Create external-sorting-algorithms.md
