- intro-to-request-response/intro-to-dns-ip.md
@MichelleGlauser this is still a work in progress but wanted to open an early PR with the work last time we met just to get the ball rolling in case someone else might work on this this weekend at the hack day (July 16).
> Lesson plan for Request/Response section: Intro to DNS and IP

- data-structures/4-semesters-of-computer-science.md
A few resources that I used to get started
> Intro to cs fundamentals resources

- FP/FP.md
Includes emoji explanation of map, reduce, and filter, and a javascript example of map.
> Start functional programming curriculum

- html-and-css/css-selector-specificity.md
Not sure it is needed, because specificity can be covered in 'IDs and Classes' since there is so much overlap.
> Remove this file

- html-and-css/intro-to-css.md
- 3 ways to add CSS to a page
- inline 
- in header
- in a seperate style sheet
- How to style elements
- Background-color
- changes the background color of an element
- accepts hex and rgba values
- Border
- elements all on one line
- can give border to different edges on the element
- top
- right
- bottom
- left
- width
- style
- dotted
- solid
- double
- dashed
- color
- How to style text
- Color
- changes the color
- accepts hex and rgba values
- Font
- change the font of text
- stored in the browser, if you want to use a fancier font link to it
- Font Size
- change the size of the text
- Sizes can be in measurements
- Pixels : when need to give a concrete size
- EM : scalable to parent's font size
- Percentage : scalable to 100%
- Tags
- tags designed to specifically change your …
> added specific things to teach

- html-and-css/intro-to-css.md
- change the color, background-color, border, font, font-size, tags, text-align, cursor
- know the 3 different ways to add CSS to a page
(moved CSS selectors objective to ids and classes)
> change and add to objective

- html-and-css/intro-to-css.md
Adjust the width and height of the image you placed in your webpage.
Change the different text tags (headers, p, and span) to different font styles and colors.
> add 2 guided practices

- html-and-css/intro-to-css.md
-not using quotation marks
-not using comments
-if something is wrong it is usually punctuation
-not using shorthand
from: https://speckyboy.com/perfecting-the-stylesheet-common-errors-made-by-css-beginners/
> add common mistakes/misconceptions

- html-and-css/basic-attributes.md
Continue building personal site by adding an image (with an alt tag) and linking to an external site.
> add guided practice instructions

- html-and-css/basic-attributes.md
- use of " vs '
- " vs '' (double quote vs two single quotes)
> add two items to common misconceptions

- html-and-css/basic-attributes.md
- 'src' is an attribute
- 'alt' is an attribute
including the ALT attribute to get accessibility started early!!
https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/staging/seed/challenges/01-responsive-web-design/basic-html-and-html5.json 
id bad87fee1348bd9aedf08812
> add some attributes for IMG tag

- html-and-css/your-first-tags.md
- Hierarchy of tags
- If it’s a header, use an `<H#>`. 
- Separate multiple paragraphs into multiple `<P>` tags.
- Helps to make the page more accessible for screen readers
- When things are ordered, use `<OL>`.
> Change SEMANTICS section

- security/security.md
Added the essential OWASP Top 10, secure coding practice, and fun XSS games.
> Basic security resources

- operating-systems/hardening.md
How to harden a linux box: for the ops and sec types very interested in the operating systems material.
> advanced linux adventure

- data-structures/what-is-a-data-structure.md
Not sure if this is something you want, but it may help ease the way into the specific data structure lessons you have in the works.
> Add overview of data structures to lesson plans.

- command-line/command-line-interface.md
> Add some more tools I like

- operating-systems/operating-systems.md
A few more things to teach and some links.
> Operating Systems

- command-line/command-line-interface.md
I think this would be a fun practice to decompress and play with variables - modify one's prompt text and add aliases. Also reordered some stuff.
> Add bashrc generator

- operating-systems/hardening.md
Add references for SELinux and IPTables and change up the order of some stuff to make more sense.
> Add references, reorder

- command-line/command-line-interface.md
Put a lot of the more advanced stuff in the advanced page.
> Remove a lot of stuff

- command-line/command-line-advanced.md
> Initial commit

- security/security.md
Removed a bunch of ops asides and threw in some specific (untested by me!) libraries to achieve the OWASP secure development objectives.
> Add suggested JS libraries, remove some esotery

- sass/sass.md
Hi Techtonica,
Here are the Sass lecture slides I created for the Hackathon on 7/15: https://docs.google.com/presentation/d/1kwiRu5C26U1Q06rpipbh2ldtJBWI-f1VwPKOKdxs9d4/edit?usp=sharing
I updated the Github repo to link to the Google slides. Please let me know what you think!
Thanks,
Larissa
> Sass presentation slides

- documentation/documentation.md
Parallels with draft deck located here: https://docs.google.com/presentation/d/18CJBM1Z6IA4MGGy6phf2bJN5gOrzQ64y1coIMcq8te0/edit#slide=id.g22b045fc2c_0_8
> lesson plan for documentation/comments; goes with completed draft deck

- html-and-css/intro-to-css.md
This is a work in progress of some additions to the CSS curriculum
> WIP: css curriculum

- testing/testing.md
This is a draft outline for #86
Let me know if this is a good start, anything to cut or expand.
Same goes for the Google Slides
=Bill
> starting point lesson outline for testing

- command-line/command-line-advanced.md
- command-line/command-line-interface.md
Added updates to the 2 command line markdown files.
Separated out advanced commands from the intro file, and added some content to the advanced markdown file.  Neither is 100% complete.
> Command line updates

- command-line/command-line-interface.md
> Command line

- runtime-complexity/lesson-plan.md
- runtime-complexity/runtime3-solving.md
- Split out optimizations
- Clean up exercises
> Finish up runtime complexity

- sorting-algorithms/lesson-plan.md
I didn't make a PR for Revision #1.
I did Bubble, Selection, and Merge.  I wasn't sure how in-depth to go.  
My biggest open-ended question:
I think it may be useful to have teacher guidance on QuickSort.  I had students break up into groups to do this, but maybe that's leaving them on their own too much.  
At the very least, I did 3 sorting algorithm lesson plans.  We can probably add more.
> Revision #2 of the Sorting Lesson 

- personal-brand/lesson-plan.md
This is the first pass at this curriculum.
> brand developing curriculum

- github-collaboration/lesson-plan.md
- open-source/open-source.md
Was trickier than I expected!
Ended up using `[Gg]ithub(?!(\.(com|md|io)|\/|-|user))`
> Proper Case GitHub

- sass/sass.md
steps on how to link .scss file to .css file
> Added steps on linking SCSS

- express-js/express-topic-outline.md
> Update  express-topic-outline.md

- data-structures/linked-list.md
Hope you like the changes that i made to the linked-list assignment... Hope I didn't make it too easy and/or give too much information...
> Update linked-list.md #165

- recursion/lesson_plan.md
- technical-assessments/README.md
- technical-assessments/coding-challenges/level-1.md
- technical-assessments/coding-challenges/level-2.md
- technical-assessments/coding-challenges/level-3.md
Added technical assessments that can be used as a prerequisite for topic outlines that need a specific technical background.
These assessments will be useful specifically for the topic outlines for `recursion`, but in the future, these assessments should be used to ensure technical capacity for `data structures` specifically for the coding challenges.
In the future, new topics can add assessment types for this.
> Add technical assessments.

- recursion/lesson_plan.md
Add details for the recursion lesson plan.
> Add details for Fibonacci

- giving-presentations/giving-presentations.md
Based loosely on slide deck but also my own experience. I hope it's helpful!
> Writing curriculum for giving presentations

- whiteboarding/lesson-plan.md
Added a Topic Outline for Whiteboarding curriculum.
> jjing-techtonica Add whiteboarding Topic Outline

- mongo-db/mongo-db.md
updated inaccurate information, removed inappropriate materials,
updated instructions
> fixed mistakes

- coding-challenges/coding-challenges.md
The link I added could be used as the entire I.P. for coding-challenges.md 
Curious to hear your thoughts @rcoh & @chi
> Add resource for coding-challenges.md

- recursion/recursion.md
- fixed a few typos
- re-wrote the motivation section to look more like the template
- changed 'independent practice' problem to a new one: factorial was listed as a practice problem twice and also appears in some of the supplementary material.
> Update / proof recursion lesson plan

- data-visualization/data-visualization.md
Pushing newest changes so @gitsteph can also work on it
> Data visualization changes

- mongo-db/mongo-db.md
Changed June back to July. Because if January is 0, then July is 6.
> Update MongoDB topic outline - Challenge

- recursion/recursion.md
Included link includes a number of relevant problems that can be solved both iteratively and recursively.
> Add link for Recursion Practice Problems.

- javascript-8/javascript-8.md
> Add mini slides to OOP slides

- README.md
Diversity and Inclusion (27. Inclusion)
>  Updated broken link for 27.Inclusuion on README.md

- diversity-inclusion-bias/inclusion.md
Added Title and Link to mini slides
> Updated Information to diversity and inclusion section

- mongo-db/mongo-db.md
Related issue: [https://github.com/Techtonica/curriculum/issues/275](https://github.com/Techtonica/curriculum/issues/275)
> Updated MongoDB topic outline (issue #275)

- react-js/react.md
add resource that explains difference between the DOM API and React DOM
> add resource react.md

- data-visualization/data-visualization.md
i just made more changes to add a new activity... didn't touch the original D3/SVG content too much though
fyi: @amychan331
> Added content to Data Visualization lesson; new interactive activity (issue #211)

- data-structures/stack.md
> Stack lesson plan

- data-structures/hash-table.md
- data-structures/linked-list.md
Updated the linked list document with a mini lesson, more supplemental materials and other notes.
> Jeremy-Sarda-Patch-1

- ajax/ajax.md
@Karla-Isabel-Sandoval here is the AJAX topic outline
> AJAX topic outline

- interviewing/technical-interviewing.md
Adds prerequisites, motivation, materials, mini lesson, challenge and common mistakes.
Still needs guided practice, independent practice and check for understanding.
> updates prerequisites and motivation

- interviewing/technical-interviewing.md
Updates sections and populates unstarted ones.
> updates sections and adds content to empty sections

- _templates/projects.md
> Refactor projects.md

- data-structures/queues.md
-add a Google Slide deck for Queue
> add slides for Queue

- databases/database-migrations.md
Slides are part of the lesson: (https://docs.google.com/presentation/d/118Fg5gaMPJBQdZV8n9dcAiYLyX5BseVUcJ1fSANdm4E/edit#slide=id.g4032745045_0_3). I'd appreciate feedback on those as well.
> Database migrations lesson

- command-line/command-line-advanced.md
- dot-profile/dot-profile.md
Guided tutorial on how to make changes to a `.profile` file. Demonstrates aliases, PATH and customization to the terminal.
> add dot-profile topic

- javascript/javascript-6-object-literals.md
- javascript/javascript-7-oop.md
- javascript/javascript-8-regex.md
- javascript/javascript-9.md
#402 
Adds Javascript 9 - Callbacks and Promises.
> Callbacks and Promises

- oauth/o-auth.md
Hi! This is a small draft but will continue to add more in the next few days.
> Update for Auth0 Lesson Plan

- networking/networking.md
This includes instructions, tips, and tricks on how to network both for extroverts and introverts alike - both online and offline.
> Update neworking.md with full lesson

- javascript/javascript-7-oop.md
cf: #409 Make sure there are explicit explanations of `this` and `new` in the JavaScript OOP outline.
https://github.com/Techtonica/curriculum/issues/409
> JavaScript-7: redefine "encapsulation" and expanding on "this" and "new"

- javascript/javascript-7-oop.md
1) Change 'var' to 'let' everywhere as per discussion with @alodahl
2) Explain using 'const' keyword in constructor as a read-only modifier
> 1) Change 'var' to 'let' everywhere; 2) Explain using 'const' keyword

- command-line/vim.md
> Vim lesson

- api/twilio-api.md
Created a lesson plan with exercises on Twilio
> Twilio Exercises

- deploying/deploying.md
> clarify material types

- optimization/optimization.md
Issue for this PR: https://github.com/Techtonica/curriculum/issues/404
Based on slides here https://docs.google.com/presentation/d/1Q1FZHrChooVHydr9Rg05T0rUFGFnzqcPmwtgMUYc6P0/edit#slide=id.g23e1eb1d92_0_54 (as of Oct 14, 2018)
> Adding Optimization lesson outline

- optimization/optimization.md
> Include slide and video links, clarify link titles

- agile-development/scrum.md
> clarify material link names, add slides

- github-collaboration/github-collaboration.md
Finish the issue  https://github.com/Techtonica/curriculum/issues/439
Update Github collaboration outline
> Github collaboration outline

- algorithms/intro-to-algorithms.md
someone else is welcome to pick up where i left off 🥇 
would also be a good idea to put some graphs in it
and pictures of sandwiches
#395
> Start intro to algorithms outline

- navigating-new-codebases/navigating-new-codebases.md
This is an article I found that I really liked for tips on navigating new codebases.
> Add link to article about navigating codebases

- functional-programming/FP.md
The link I added is an awesome resource I found a few years back. It's interactive, so it's great for getting immediate results on whether or not your solution is correct.
> Add resource for beginners about functional programming

- javascript/javascript-7-oop.md
The previous example got into a lot of details about private variables and patterns for how to achieve private variables. This seems like a lot of detail for an early lesson on OOP.
Also, consider replacing `Overriding` with `Abstraction` to match the slides.
> Simplifies Encapsulation explanation

- functional-programming/FP.md
- Fix a typo in a link
- Add some other example laguages (let me know if this is out of scope!)
- Formatting
> Suggested improvements

- operating-systems/operating-systems.md
Outline update, with heavier focus on processes and multitasking.
> Operating Systems Outline

- api/apis-and-json.md
Hi everyone, I talked with @MichelleGlauser and she recommended I make a pull request. 
I was looking over the “API and JSON” part of the curriculum. I saw an opportunity to add a few notes that will hopefully enhance the material your students are covering. Below is an outline of why I made the additions to the current curriculum.
- Status codes are important for working with APIs. A status code is the simplest and most consistent way programmers can verify  they are communicating with the REST API. If there are errors the status code can give clues as to where they should start troubleshooting.
- HTTP methods should be mentioned. GET and POST are used in the examples but not explained. Take a minute to point out they are not the only ones but the ones they will use the most often. Plus …
> Trewaters api

- git-version-control/git-version-control.md
githug is an interactive tutorial that makes sure you know how to use most git commands. I've suggested completing at least up to `#32: checkout` but please feel free to take a look and amend my suggestion. I want to say to complete even more (merge! rebase! bisect!!) but don't want to overwhelm everyone. I'd like to revisit `merge`, `squash`, and so on before we get to open source week in March!
> Add githug as a fun resource for learning git.

- testing-and-tdd/jasmine-testing.md
started but didn't finish creating a testing topic. I could finish it over the next few days.
Please look at it too because I wasn't sure if it was okay to combine Jasmine/Mocha/Chai into the same lesson. The title of the issue says Jasmine but the bullet points are about Mocha/Chai.
Your comments are welcome!
> update jasmine testing

- command-line/command-line-advanced.md
Remove unused template sections. Fix some markdown formatting. 
Still needs environment variable part of lesson to be added.
> Clarify advanced command line lesson. 

- command-line/command-line-interface.md
TLDR's verisons of man pages are simple and straightforward and task oriented. Very helpful in situations where you have half a memory of the command you're trying to use.
> Added TLDR (simple man pages) to list of suplemental materials

- projects/portfolio/portfolio-webpage-1.md
I found a link to a bunch of portfolio websites. Not sure if I need to format the link differently or if you want the link directly to a website.
> Update motivation for portfolio

- bootstrap/bootstrap.md
- git-version-control/gitignore.md
- jquery/jquery.md
- projects/final-project/final-project.md
- sass/sass.md
Fixes https://github.com/Techtonica/curriculum/issues/539.
- bootstrap
- .gitignore
- jquery
- final project
- sass
> Change references to Atom to VS Code.

- projects/recipe-page/phase-2-css-prompt.md
I use Digital Color Meter all the time, so I added it under the existing reference to htmlcolorcodes.com.
> [CSS 2] Add instructions for using Digital Color Meter to the CSS-phase-2 lesson.

- practice/students.md
Learning to create pull request
> add my name

- data-structures/deque.md
Per conversation in https://github.com/Techtonica/curriculum/issues/537, it's likely easier to add additional reading than it is to add a YouTube video (there aren't really any good ones that I could find on the A-Steal Algorithm).
> Added additional reading to deque lesson

- command-line/command-line-interface.md
- Changed from paragraph to list of motivations.
- Added examples such as using npm & error messages.
- Added example website - installation for express.js
> Update Motivation on command-line-interface.md

- ethics/ethics.md
- Added an Independent Practice exercise to brainstorm about an ethical problem & approach to resolve.
- Added real example to Privacy section re: teen girl's pregnancy being revealed to her parents via ads.
- Added to Human & Machine Bias. 
- Added consideration to Agency that managers may not consider ethics before assigning tasks.
> Additions to ethics.md

- testing-and-tdd/enzyme-testing.md
> Create curriculum topic outline for enzyme

- women-in-tech-resources/resources-list.md
Updated the WIT Resources Lesson to just be a list of resources. I wasn't able to find links for everything @judytuna listed in the issue, so let me know if there are other specific links I should add!
> Women in tech resources - Issue 183

- javascript/javascript-7-oop.md
Project following this assignment requires in depth understanding of classes. This (or another interactive resource) as a supportive addition to the "classes" explanation in this section may help the OOP project more understandable.
> Insert Intro to Classes CodeAcademy Course

- projects/take-home-problems/backend.md
Asks candidates to build a couple of API endpoints which join and aggregate data from a public data set for consumptions by a hypothetical mobile app.
> Introduce a backend take home interview problem

- women-in-tech-resources/resources-list.md
Added some suggestions to motivation and meetups and conferences in India. Some channels and chat 
groups where women can chat safely.
> Added some resources in title Motivation and India

- projects/recipe-page/phase-3-bootstrap-prompt.md
Added the bootstrap v-4 support.
> Update phase-3 bootstrap issue #571

- ajax/ajax.md
- css/css.md
- css/media-queries.md
- databases/database-migrations.md
- databases/relational-databases.md
- databases/sql.md
- datetime/datetime.md
- html/html.md
- javascript/javascript-1.md
- javascript/javascript-2.md
- javascript/javascript-3.md
- javascript/javascript-6-object-literals.md
- javascript/javascript-7-oop.md
- javascript/javascript-8-regex.md
- jquery/jquery.md
outdated w3schools links were replaced with new and updated links (mdn(mostly) , tutorialspoint, javatpoint)
>  replaced w3schools links with updated links

- git-version-control/git-version-control.md
> Git version control slides reviwed

- professionalism/professionalism.md
@alodahl  I added precise description of slides in the lesson section and put the video links in supplement material sections
> Changes in lesson section and supplement material

- ergonomics/ergonomics.md
improved motivation section for ergonomics.
@alodahl
> improved the motivation section for ergonomics.

- women-in-tech-resources/resources-list.md
> added more resources

- learning-to-learn/learning-to-learn.md
Changes in lesson and supplement material sections. @manaswinidas
> Update learing-to-learn. md

- security/web-security.md
Closes #535 .
Changes:
- Added some details about XSS and CSRF attacks.
- Rearranged headlines in outline for better flow like lessons before misconceptions.
- Simplified questions in self assessment which have short but understanding based answer.
- Added MDN as a source
- Other minor changes like typo fix and and a new point in misconception
- Changes in Slides(XSS/CSRF definitions and use cases)
> Changes in web-security

- command-line/dot-profile.md
> Update dot-profile.md 

- roles-in-tech/entrepreneurship.md
Fixed #94 Updated dead links and proof-read it.
> Updated Security.md

- roles-in-tech/developer-advocate.md
> Modified Motivation section and added lessons 

- women-in-tech-resources/resources-list.md
Fixes #560 
Added
1. Ladies storm hackathon group
2. SWE group
3. Lean In CS&E Student Chapter group
4. Palantir Scholarship
5. SWE Scholarship
> Fixes #560 added resource to women in tech resources

- professionalism/professionalism.md
- roles-in-tech/developer-advocate.md
> added Slideshow

- optimization/optimizing-your-react-node-project.md
> Optimization for Node/React Projects

- javascript/javascript-3.md
> modified movie goers function

- github-collaboration/github-collaboration.md
> Added git remote usage

- roles-in-tech/dev-ops.md
A short description to start with the role of becoming a  DevOps in today's world.
Fixed Issue #93.
> Added DevOps to Roles in Tech

- roles-in-tech/sales-engineering.md
> created sales engineer outline issue 

- javascript/javascript-9.md
Add 'Introduction to Promises' link in Supplemental Materials section of javascript-9.md file.
Augment Promises outline #597
> Augment Promises outline issue #597

- women-in-tech-resources/resources-list.md
add the link of 'women who go' & 'moms in tech' in resources-list.md file.
> Add a suggestion to our Women in Tech Resource List!  issue#560

- css/css.md
improve motivation section of css.md file
> Strengthen "Motivation" sections. issue #288

- roles-in-tech/technical-writing.md
A short description about  the career in the field of Technical Writing.
Fixed Issue - #671 .
> Added Technical Writing to Roles in Tech

- open-source/open-source.md
> Small typo in Common Mistakes sectio

- command-line/command-line-advanced.md
- deploying/deploying.md
Added link to the video. 
Fixes #513
> Find or make a video for Advanced Command Line topics

- learning-to-learn/learning-to-learn.md
Fixed typo errors in learning-to-learn.md file.
issue fixed #697
> fixed typo errors in learning-to-learn.md file

- roles-in-tech/qa.md
> created outline for qa engineer

- roles-in-tech/machine-learning.md
add the topic outline in machine-learning.md file
Fixed #96
> add topic outline in machine-learning.md file

- css/css.md
- data-structures/stack.md
- html/html.md
Issue #570 The HTML, CSS and Stack Topic outlines seemed to be alright and has the proper information under the proper headers. Please check it out to make sure, I just edited some typos and indented the outlines.
> Topic outlines

- learning-to-learn/learning-to-learn.md
> Test out tutorial for rest API

- databases/mongo-db.md
> added instructions for the video link

- api/REST-API.md
Fixes issue #653 
Link for the slideshow: https://docs.google.com/presentation/d/1ZdnhhGbwyJcmgPnTn6eeHjdhekUvo0ht70MwC7Ll5zw/edit#slide=id.g22ccc6273c_1_211
> Made the outline for Rest api

- oauth/authorization.md
Hi Mentors, I'm just going to merge what is here.  Could you please give Nirmal "Easy" points for this, since he was less than halfway done? No need to "review", since we already have a participant willing to pick up the rest of this issue. Just approve once it is in the scoresheet.
Worked on issue #583
> Authorizing user in Nodejs with Auth0

- command-line/command-line-advanced.md
add videos regarding commands **wc**, **sort**, **cut**, **xargs**,**apropos**, **sed**, **awk**, **pushd**, **popd** in the materials section of the command-line-advanced.md file.
Fixed #712
> add more videos in materials section of command-line-advanced.md file and fixed some typo errors

- javascript/javascript-2.md
- javascript/javascript-3.md
- javascript/javascript-4.md
- javascript/javascript-5.md
- javascript/javascript-6-object-literals.md
- javascript/javascript-7-oop.md
- javascript/javascript-8-regex.md
Update prerequisite links on the javascript lessons  - I realize there is more to do here, but this seemed to be a good chunk to update.
> Issue #730

- README.md
- learning-to-learn/learning-to-learn.md
- professionalism/professionalism.md
- roles-in-tech/roles-in-tech.md
Fixes the Onboarding part of Issue https://github.com/Techtonica/curriculum/issues/730
Consolidates these PRs:
- https://github.com/Techtonica/curriculum/pull/736
- https://github.com/Techtonica/curriculum/pull/735
- https://github.com/Techtonica/curriculum/pull/734
> Linked all Onboarding Prerequisites and included them in README

- learning-to-learn/learning-to-learn.md
I have completed "Ethics in SE" based on its outline. The issue is #396
> Completed "Ethics in SE" slideshow issue #396

- command-line/command-line-interface.md
Modified file as per the comments in #643. The issue for this PR is #727.
> Modified file command-line-interface

- roles-in-tech/security.md
mention about OSCP certification in security.md file and also in security slides and fixed some typo errors in security.md file
Fixed #719
> mention about OSCP certification in security.md file and in slides also

- algorithms/searching.md
separate supplement resources from requires materials in searching.md file and fixed some typo errors 
Issue Fixed #570
> separate supplement resources from requires materials in searching.md

- roles-in-tech/machine-learning.md
> Modified outline and updated motivation section.

- command-line/keyboard-shortcuts.md
updated [Keyboard shortcuts lesson](https://github.com/Techtonica/curriculum/blob/master/command-line/keyboard-shortcuts.md) & Fixed issue #728
> Added popular mac utilities link in #728

- interviewing/whiteboarding.md
Modified slide show as commented. The issue number is #744
> Modify Slide Show 'Intro to Git'

- women-in-tech-resources/resources-list.md
added a scholarship program "Venkat Panchapakesan Memorial Scholarship" which is for women and non-binary engineers
> #777 added in scholarship section

- data-structures/deque.md
- data-structures/trees.md
#570 
https://github.com/Techtonica/curriculum/blob/master/data-structures/trees.md
> Binary Search Trees, B Trees

- datetime/datetime.md
All the slides having access to me I have formatted. Fixed issue #600
> Formatted all the techtonica templates at issue #600

- ethics/ethics.md
Add subtitles/captioning for the YouTube video https://youtu.be/NodKFuUocQY in the English language and also fixed some typo errors in the ethics.md file.
Issue Fixed #702
> Add subtitles to one of the advance command line video

- chrome-developer-tools/chrome-developer-tools.md
separate supplemental resources from the material section in chrome-developer-tools.md file and fixed some typo errors
Issue Fixed #570
> separate supplemental resources from material section

- runtime-complexity/memoization.md
Separate supplemental resources from the materials section in memoization.md file and also fixed some typo errors & white spaces.
Issue Addressed #570
> Separate supplemental resources from materials section 

- css/reset-css.md
Create a template outline for reset.css in css directory and add a guided practice section in reset-css.md file
Issue fixed #780
> add guided practice section in reset-css.md file

- roles-in-tech/product-manager.md
> Created 'Role in Tech: Product Manager' outline

- vs-code/vscode.md
> Updated and added vscode workflow tips.

- javascript/javascript-maps.md
Issue #795 Added maps and sets explaination. Also i've added a short video in material section.
> created javascript-maps.md and explained maps sets

- javascript/javascript-4.md
Added questions in check for understanding under the topic javascript-4
Fixed issue #700
> Added questions in CfU  javascript-4

- javascript/javascript-5.md
Added questions in CfU Javascript-5
Fixed issue: #700
> Added questions in CfU Javascript-5

- databases/relational-databases.md
Added treehouse resource to Relational Databases outline in guided practice.
Updated the time also.
Fixed issue #800
> Added resource to relational database

- javascript/first-js-oop-project.md
> mini project for js outline added

- interviewing/technical-interviewing.md
Formatted Techtonica Slideshows at issue #598 . I have edited all the slides as per instructions. Slide no 12, 26 is ok as told by @alodahl. Slide no 30 is not available to me.
> Formatted all the slides as per guidelines

- resume-writing/resume-writing.md
> Added questions in CfU resume-writing

- css/css.md
> Added Guided Practice and Independent Practice to css.md

- command-line/command-line-interface.md
Added bash resource to command-line-interface
Fixed issue #820
> Added resource to command-line-interface

- vs-code/vscode.md
Formatted all the slides present at #599 according to guidelines.
> Formatted Techtonica Slides 2/3

- learning-to-learn/learning-to-learn.md
- personal-brand/personal-branding.md
Moved additional resources to supplemental resources
Fixed Issue: #837
> Seperated supplemental resources-Part 9

- seo/seo.md
Added questions in CfU in file seo.md
fixed issue #700
> Added questions in CfU 

- html/html.md
> Added questions in CfU -  html.md

- recursion/recursion.md
PR #786 
recursion make it quite easy to calculate gcd of two numbers.I added one challenge of GCD with full explanation . under issue no. #570
> #786 added one example in challenge section

- command-line/command-line-interface.md
> Added Questions in CfU - Command line interface

- css/css.md
> Added questions in CfU -  css.md

- ajax/ajax.md
- api/apis-and-json.md
- api/twilio-api.md
- data-visualization/data-visualization.md
- databases/data-models.md
- databases/database-migrations.md
- databases/sql.md
- express-js/express.md
- javascript/javascript-9.md
Separate supplemental resources from the material section of the following files:
and I find the outline of the following file looks fine:
Issue Fixed #832
> separate supplemental resources from materials

- ethics/ethics.md
- financial-literacy/financial-literacy.md
- roles-in-tech/developer-advocate.md
> sperated supplemental resourcses from required materials

- accessibility/accessibility.md
- datetime/datetime.md
- diversity-inclusion-bias/inclusion.md
- interviewing/whiteboarding.md
- javascript/javascript-3.md
- javascript/javascript-4.md
- seo/seo.md
- writing-readable-code/writing-readable-code.md
Fixed issue #834
These topics look fine:
https://github.com/Techtonica/curriculum/blob/master/interviewing/week-3-whiteboard-challenges.md
https://github.com/Techtonica/curriculum/blob/master/personal-brand/personal-branding.md
> Separated supplemental resources

- best-practice-in-development/best-practice-in-client-side-development.md
add the importance of lorem ipsum & lorem picsum in best-practice-in-client-side-development.md file inside the best-practice directory.
Issue Fixed: #819
> add importance of lorem ipsum text

- javascript/javascript-6-object-literals.md
> Added question in CfU- JavaScript6

- accessibility/accessibility.md
add about Lighthouse extension in accessibility.md file and also fixes some typo errors.
Issue Fixed: #815
> add about Lighthouse extension in accessibility.md file

- writing-readable-code/writing-readable-code.md
> Added questions in CfU - writing readable code

- personal-brand/personal-branding.md
> Added Question in Check for Understanding - Personal Branding

- javascript/javascript-3.md
> Added question in Check for Understanding -JavaScript 3

- interviewing/whiteboarding.md
> Added questions in CfU - whiteboard

- diversity-inclusion-bias/inclusion.md
> Added questions to CfU - inclusion

- github-collaboration/github-collaboration.md
Created 15 tests for following assignments:
2/28, 2/8, 3/11, 3/12(# 80), 3/12(# 96), 3/13, 3/15, 3/18, 3/22, 3/27, 3/28, 3/29, 3/4, 3/5, 3/6
issue #859
> Created 15 automatic tests Repl.it classroom Part 2

- personal-brand/personal-branding.md
Added tests for following assignments:
3/7, 3/8, 4/1, 4/2, 4/3, 4/4, 4/5, 2/21, 2/4, 2/7, 3/1, 4/10
2/5 have not any test cases:
Following assessments are not very clear:
2/6, 2/14, 3/14
Issue #866
> Created 15 automatic tests 45/45

- financial-literacy/financial-literacy.md
created 15 tests for following assignments:
1/28, 1/29, 1/30, 1/31, 2/11, 2/12, 2/13, 2/15, 2/19, 2/20, 2/22, 2/25, 2/26, 2/27(# 27), 2/27(# 75)
Issue #851
> Created 15 automatic tests for repl.it classroom

- command-line/keyboard-shortcuts.md
Fixed issue #818 
Added **General Mac Tips** Section for 'Trackpad' and 'Pairing a Magic Mouse'.
> Updated keyboard-shortcuts.md

- databases/relational-databases.md
> Modified things to things teach section, added supplement section and questions in check for understanding

- agile-development/scrum.md
- databases/database-migrations.md
- databases/mongo-db.md
- databases/relational-databases.md
- security/web-security.md
> Modifies and adds companies to the motivation section

- asking-good-questions/asking-good-questions.md
- command-line/command-line-advanced.md
- command-line/command-line-interface.md
- command-line/dot-profile.md
- command-line/keyboard-shortcuts.md
- networking/networking.md
- operating-systems/operating-systems.md
- vs-code/vscode.md
> Separated supplemental resources- part 8

- roles-in-tech/security.md
Fixes Issue:  (https://github.com/Techtonica/curriculum/issues/788)
> Add links to roles in security outline

- javascript/javascript-5.md
- javascript/javascript-6-object-literals.md
- javascript/javascript-8-regex.md
- jquery/jquery.md
> Fixed Materials sections, Part 5

- agile-development/intro-to-agile.md
- agile-development/scrum.md
- databases/mongo-db.md
- deploying/deploying.md
- oauth/o-auth.md
- recursion/recursion.md
- runtime-complexity/memoization.md
- security/web-security.md
- testing-and-tdd/enzyme-testing.md
Separate supplemental resources from the materials section and also fixes some typo errors in the following files:
I'm unable to find this file
Issue Fixed: #831
> Separate supplemental resources from materials section

- agile-development/intro-to-agile.md
- data-structures/deque.md
- data-structures/hash-tables.md
- data-structures/intro-to-data-structures.md
- data-structures/queues.md
- data-structures/stack.md
- functional-programming/FP.md
- jquery/jquery.md
- testing-and-tdd/jasmine-testing.md
- testing-and-tdd/testing-and-tdd.md
> adds companies and examples to motivation section

- chrome-developer-tools/chrome-developer-tools.md
- git-version-control/git-version-control.md
- github-code-storage/github-storage.md
- javascript/javascript-5.md
- javascript/javascript-6-object-literals.md
- javascript/javascript-8-regex.md
- jquery/jquery.md
- pair-programming/pair-programming.md
- requests-and-responses/requests-and-responses.md
Fixed Issue #835 
> * [x] https://github.com/Techtonica/curriculum/blob/master/requests-and-responses/intro-to-dns-ip.md
> * [x]  https://github.com/Techtonica/curriculum/blob/master/projects/first-assessment.md
> * [x]  https://github.com/Techtonica/curriculum/blob/master/pair-programming/pair-programming.md
> * [x]  https://github.com/Techtonica/curriculum/blob/master/git-version-control/git-version-control.md
> * [x]  https://github.com/Techtonica/curriculum/blob/master/projects/recipe-page/phase-1-html-prompt.md
> * [x]  https://github.com/Techtonica/curriculum/blob/master/github-code-storage/github-storage.md
> * [x]  https://github.com/Techtonica/curriculum/blob/master/chrome-developer-tools/chrome-developer-tools.md
> * [x] …
> Fixed Issue #835

- ajax/ajax.md
- databases/data-models.md
- databases/sql.md
- mobile-development/mobile-development.md
- professionalism/difficult-workplace-situations.md
- roles-in-tech/sales-engineering.md
> adds companies to motivation section

- databases/installing-postgresql.md
- javascript/javascript-maps.md
- roles-in-tech/entrepreneurship.md
- roles-in-tech/technical-program-manager.md
- vs-code/vscode.md
added reference for javascript-maps.md and postgre-installation.md
> Added reference to files

- roles-in-tech/security.md
I have added some links for copied text for more reference.
> Add Reference section

- javascript/event-recommender-part2.md
Fixes https://github.com/Techtonica/curriculum/issues/804
The main point was to specify that the jQuery ui files should be in a separate file, but then I realized we didn't have any instructions for adding jasmine tests so I added some.
Also moved some things around to make it clear that we're working with different files and concepts. 
@alodahl could you take a look at this, please? Thanks!!
> EventRecommender project part 2: clarify and extend jasmine instructions

- command-line/command-line-advanced.md
- command-line/dot-profile.md
Fixes https://github.com/Techtonica/curriculum/issues/904
> convert check for understandings into questions- part 3

- css/css.md
- css/reset-css.md
- debugging/debugging.md
- roles-in-tech/machine-learning.md
add cite in some content of following files:
> add cite in some content of some files

- javascript/event-recommender-part2.md
https://github.com/Techtonica/curriculum/issues/910
> Fix Typos in Event Recommender guidelines

- chrome-developer-tools/chrome-developer-tools.md
Converted checks for understanding into small-group questions.
> converted checks for understanding q's -- chrome dev tools

- javascript/javascript-7-oop.md
A few small changes that make the wording less confusing
> Tiny updates

- projects/portfolio/portfolio-webpage-1.md
Encourage good GitHub practices by having apprentices commit multiple times rather than just once at the end
> Update GitHub instructions for Portfolio part 1

- practice/students.md
> added a little something extra

- javascript/first-js-oop-project.md
Added instructions for putting functions on the Event class
> Added functions

- git-version-control/git-version-control.md
Fixed issue #700
Should I add the Challenge section in Projected Time?
> Sniemar git version control

- pair-programming/pair-programming.md
> Sniemar pair programming

- asking-good-questions/asking-good-questions.md
- vs-code/vscode.md
> Added `Check For Understanding` questions to VSCode and Asking Good Questions lessons

- women-in-tech-resources/resources-list.md
And also swapped the bracket syntax for LinkedIn.
BTW, I just discovered Techtonica. It's such an amazing organization.
> Added Write/Speak/Code to conferences

- html/html.md
> Added cheatsheet link to supplemental resources

- conflict-resolution/conflict-resolution.md
- networking/networking.md
Fixes #916
I converted the "Check for Understanding" section for the Networking lesson to questions, and created the same section for the Conflict Resolution lesson. I also fixed some minor issues I noticed.
> Converting "Check for Understanding" into questions (Issue #916)

- javascript/javascript-7-oop.md
A few changes to the OOP lesson:
- I switched the implementation of `checkOut()` to not use a Loan class -- I think that will make it easier to follow and a better example of an OOP project without a DB
- Add syntax highlighting
- Move advanced material to Challenge section
- Made a few other small fixes
> OOP lesson updates

- jquery/jquery.md
- Replace paid tutorial with free one
- Make some edits
> Update jQuery lesson

- requests-and-responses/intro-to-dns-ip.md
- requests-and-responses/requests-and-responses.md
> Adding check for understanding

- css/media-queries.md
Remove extra whitespace in the 'code' sections and normalize indent to 2 spaces.
> Remove useless whitespace from media-queries.md

- javascript/event-recommender-part2.md
- javascript/event-recommender.md
> Fixed grammatical errors in event recommender files

- writing-readable-code/writing-readable-code.md
This pull request addresses [984](https://github.com/Techtonica/curriculum/issues/984)
Motivations for writing readable code lesson updated. 
Included more robust explanation and links with examples.
> update motivation for writing readable code

- assessment-objectives/6.md
Links for the 6th Week assessment has been updated  and are now functional
> Broken Links Updated for Week 6 assessment

- projects/take-home-problems/backend.md
```.mode csv``` was missing from original instructions. I spent time trying to import those csv files until I found instructions at google: https://www.sqlitetutorial.net/sqlite-import-csv/
> Added instructions to switch to csv mode in sqlite3

- projects/minimal-api-project.md
> updated with guide for the outdated treehouse workshop

- github-collaboration/github-collaboration.md
Added some more quesitons related to the github collaboration md
https://github.com/Techtonica/curriculum/blob/master/github-collaboration/github-collaboration.md
> Added more questions to check for understanding portion of file

- agile-development/intro-to-agile.md
This PR fixes issue #997 with an updated table of contents for the Intro to Agile curriculum.
I've also updated the slides on a a personal copy: https://docs.google.com/presentation/d/1lt4w3GAXRh3Yx4Vbn6F1oZSKPH6mHl-U_1lnApHNyj0/edit?usp=sharing
I've transferred ownership of the Google Slides file to techtonicaorg@gmail.com, as well.
Let me know if there's any changes you'd like to see!
> Update table of contents for Intro to Agile

- accessibility/accessibility.md
- giving-presentations/giving-presentations.md
- professionalism/building-confidence.md
In this PR I convert check for understandings into questions, of issue #1005
> convert check for understandings into questions (Part C)

- projects/minimal-api-project.md
- women-in-tech-resources/resources-list.md
- women-in-tech-resources/resources-list.md.orig
Splitted General and SF Bay Area into their own categories.
Still have a couple of links in India to review. 
Specifically categories naming
> Splitted General, SF and India into own categories

- financial-literacy/financial-literacy.md
- professionalism/difficult-workplace-situations.md
Direct participants to form small groups.
Edit questions to address Objectives, including discussing a hypothetical situation.
Add 20 minutes to total lesson time.
> Update Check for Understanding Section

- ethics/ethics.md
- interviewing/negotiating.md
Updated the check for understanding for the negotiation page.
> updated check for understanding

- javascript/javascript-2.md
added additional questions in Javascript-2.md
addresses #1006
> Added more check for understanding questions in Javascript-2.md

- agile-development/scrum.md
> Updated roles in agile

- css/media-queries.md
Hi,
please have a look at my solution to this markdown problem: I did not changed the numbers as wished, but I had to put some extra spaces to the codeblock, otherwise the ordered list will not continue with the count.
Hope I could help you with this issue!
> Fix markdown formatting in lesson outline #1031

- css/media-queries.md
Indentation mismatch in css/media-queries.md file
caused the list numbering to mess up.
> Fixed markdown issue for media-queries page

- reading-and-writing-documentation/documentation.md
and markdown link from github to supplemental materials
fixes #1006
> Added check for understanding questions

- testing-and-tdd/integration-testing.md
> Changed objectives and outline

- git-version-control/gitignore.md
> Sniemar gitignore

- agile-development/intro-to-agile.md
> updated waterfall vs agile and added single slide for differences

- mobile-development/mobile-development.md
- roles-in-tech/developer-advocate.md
- roles-in-tech/sales-engineering.md
Convert Check for Understanding Into Questions ( Part V ) #1025 
- Split questions in bullet points
- Added 3 questions
- Properly edited one question that was bad formatted
> Issue 1025 - Convert Check for Understanding Into Questions ( Part V )

- python/python.md
> Fix punctuation in python.md

- javascript/basic-js-practice.md
- javascript/javascript-6-object-literals.md
- runtime-complexity/runtime-complexity.md
I added some examples of companies (Facebook, Pinterest and Google) to the Motivation sections of runtime-complexity.md and javascript-6-object-literals.md. Please let me know if there is anything I can improve! Thanks!
> Strengthen "Motivations" sections: Part 3c #854

- databases/mongoose.md
Addressed to issue #966 .
@alodahl 
I have added a new markdown to databases folder with the name mongoose.md
Kindly check and revert back. If any changes are required do let me know.
> Lesson on Mongoose ORM

- data-structures/deque.md
- data-structures/linked-lists.md
Converted Check for understanding into questions for:
https://github.com/Techtonica/curriculum/blob/master/data-structures/deque.md
https://github.com/Techtonica/curriculum/blob/master/data-structures/linked-lists.md
https://github.com/Techtonica/curriculum/blob/master/data-structures/hash-tables.md
This closes issue #1021
> converted Check for Understanding to questions (Part R)

- roles-in-tech/data-science.md
- roles-in-tech/entrepreneurship.md
- roles-in-tech/security.md
Convert check for understandings into questions (Part U) #1024 (3/3)
> Add Checking for Understanding Questions

- github-collaboration/github-collaboration.md
- practice/apprentices.md
Felt students.md was changed to apprentices.md
> change practise/students.md to practise/apprentices.md

- agile-development/intro-to-agile.md
Changed titles in materials and supplemental materials to the actual titles.
Added type of resource and time to read/watch
> fixed link titles

- roles-in-tech/technical-writing.md
Add some links about technical writing to the Supplemental Materials section. Related issue: #1067 1067
> Add some links

- welcome-tips-rules/tech-industry-tips.md
- TODO: find free distraction-control app
- TODO: find a anonymous or public record example of someone getting fired for private email or IM's so it's a stickier story
> draft tech-industry-tips improvements about distractions/deep work

- .gitignore
- CONTRIBUTING.md
- package-lock.json
- package.json
Add npm script to scan for potential dead links:
* `npm run validate-links`
Once you've checked out the project, be sure to run `npm i` to install the packages. And then you'll be able to run the command.
I added instructions to `CONTRIBUTING`. Feel free to move it to another place if it's not right.
<details>
<summary><code>validate-links</code> result</summary>
<pre>
CONTRIBUTING.md: no issues found
README.md
105:4-105:127  warning  Link to https://github.com/Techtonica/curriculum/blob/master/javascript/event-recommender.md is dead                                                                             no-dead-urls  remark-lint
105:4-105:127  warning  Link to unknown file: `javascript/event-recommender.md` …
> Scan .md files for dead links

- git-version-control/git-version-control.md
Adding a video tutorial to help with understanding the forking/pull request on GitHub
> Video Tutorial on Forking/pull Request for GitHub

- git-version-control/git-version-control.md
This is a beginner's tutorial on Github.
> Added Github basics tutorial

- databases/relational-databases.md
Hi,
I've added a link to the visual representation of the join examples.
Please let me know if it is as intended
#1112 cc @alodahl
> docs: add link to visual representation of join exmaples

- git-version-control/git-version-control.md
adding a helpful link to the GitHub version control lesson. This link has a nice visual diagram that clarifies the basic actions/commands and the movement of the files/content with Git.
> adding a new link for materials

- github-code-storage/github-storage.md
I found this typo and thought it would be good practice to see how to make a pull request :)
> added the typo-fixes branch

- solving-coding-challenges/solving-coding-challenges.md
https://github.com/Techtonica/curriculum/issues/1080
**Questions**
- Is this the appropriate level of difficulty and explanation? Not sure where the apprentices will be at in the curriculum when learning this. Let me know if you'd like me to adjust!
> Outline for Solving Coding Challenges

- practice/apprentices.md
Added my name to the apprentices' doc, VSC automatic styler updated other lines with excess spaces as well.
> Add my name per GitHub Collaboration assignment instructions

- practice/apprentices.md
> Added name

- README.md
After creating the mostly finalized H1 2020 roadmap, reorganize the README to match.
> sync README with H1 2020 roadmap

- testing-and-tdd/jasmine-testing.md
- testing-and-tdd/mocha-testing.md
For https://github.com/Techtonica/curriculum/issues/1081
These links used to point to one slide show - it's now been split into two slideshows, to reflect that there are 2 separate lessons!
Please also look over the new slideshows as a part of reviewing this, since some content has changed.
> Split jasmine & mocha slides

- oauth/o-auth.md
The latest Auth0 sample code for React comes with a functioning
logout button. The files referenced in the instructions no longer exist
and have been replaced with an external Auth0 package.
Addresses https://github.com/Techtonica/curriculum/issues/969
> Remove step 4 - logout button

- backend/1_intro_to_backend.md
> Backend intro first draft

- README.md
- agile-development/intro-to-agile.md
@vegetabill are we making mongo an elective now? Based on how you re-arranged the readme, I did not add this lesson to the roadmap or the objectives.
addresses #967
> Add mongoose outline to readme

- projects/eventonica/eventonica-part5-express-backend.md
Addressing https://github.com/Techtonica/curriculum/issues/1158
I went through the steps and added links that I found helpful.
For the Challenge section, I added two options. Please let me know if these are of appropriate difficulty or if anything is unclear. Thanks!
> Updates to Eventonica - Part 5

- interviewing/technical-interviewing.md
- welcome-tips-rules/tech-industry-tips.md
in particular would love feedback on the "While we're on that subject" paragraph
> Issue 1116 - resolve TODO's in industry tips

- projects/eventonica/eventonica-part6-postgres.md
I'd appreciate any feedback on this lesson! I am not using an ORM because I'm not sure if the cohort will have encountered ORMs by the time they do this project. I am assuming that they have some familiarity with SQL and basic queries. I am also assuming that they have a way to execute queries on their machine (e.g., psql, PGAdmin).
The challenge questions require learning how to use Postgres constraints and using SQL Joins. Please let me know if the difficulty level is appropriate.
This addresses https://github.com/Techtonica/curriculum/issues/1159
> Adding postgres eventonica lesson

- api/http-request-practice.md
- api/intro-to-http.md
There was no basic HTTP lesson and we got feedback that our foundational skills were missing so I split off and expanded the HTTP portions of my HTTP request practice lesson.
> [API] Added "Intro to HTTP"

- api/REST-API.md
I wasn't really able to follow this lesson so I simplified it.
> [REST-API] rewrite REST lesson to be more clear

- github-collaboration/github-collaboration.md
Added a study link for github collaboration guide.
> Add github collaboration guide

- react-js/react-hooks.md
**Questions**
How much React practice will they have between the Intro to React lesson and this?
Is this lesson an OK level of difficulty/detail?
> React hooks lesson plan

- css/BEM-style.md
Added the lesson on BEM . I have kept the md files inside the css section itself.
Addressed to issue number [#1175]("https://github.com/Techtonica/curriculum/issues/1175").
> Adding BEM Outline

- functional-programming/FP.md
- javascript/javascript-7-oop.md
- javascript/javascript-maps.md
- objectives/week-6-assessment.md
- prework/week2LoopsExercise.js
- projects/Eventful-API-test-page/eventfulAPI.js
- runtime-complexity/runtime1-analyzing.js
- testing-and-tdd/mocha-testing.md
> Checked whether let and const are used properly and then changed accordingly

- README.md
- api/apis-and-json.md
- data-structures/deque.md
- data-structures/intro-to-data-structures.md
- data-structures/linked-lists.md
- data-structures/queues.md
- data-structures/trees.md
- datetime/datetime.md
- functional-programming/FP.md
- javascript/javascript-1-variables.md
- javascript/javascript-2-array-functions.md
- javascript/javascript-3-conditionals.md
- javascript/javascript-4-loops.md
- javascript/javascript-5-switch.md
- javascript/javascript-6-object-literals.md
- javascript/javascript-7-oop.md
- javascript/javascript-8-regex.md
- javascript/javascript-9-async.md
- javascript/javascript-maps.md
- recursion/recursion.md
Fixes #1229 
Updated and Renamed the files. Please review! @vegetabill
> Renamed all JavaScript lessons and updated links to them.

- Angular/angular.md
- electives/Angular/angular.md
Closes issue #1227 
@vegetabill Please review my Pull Request. I have added the necessary links and resources on Angular. If any further changes are needed, kindly let me know. Thanks.
> Added Elective Lesson on Angular

- css/BEM-style.md
addresses #1196 
Based on the changes made in resolving issue #1195 , the necessary changes have been made to their respective slideshow.Making a PR with a single typo fix as instructed on the issue.
> Completed issue #1196 for verifying slideshows based on #1195

- projects/eventonica/eventonica-part6-postgres.md
Closes Issue #1218 - Fix typo in eventonica-6 instructions
How to Submit
In additional to the usual steps: => In addition to
> Fix typo in eventonica-6 instructions

- README.md
Fixes #1277
* Most of the lists had line spaces in this.
* Removed the line spacing so no new paragraphs inside list are created.
> **Note:** I am a mentor previously so thought of just helping out this particular one. 😊
> Updated the lists to remove paras.

- data-structures/hash-tables.md
Closes: #1286 
@Kundan28 Sir please review it
> Fixed broken link in Hash Table Topic Outline

- objectives/9.md
Closes Issue #1264 - Find and fix link for Assessment 9 objectives
Fixed the links. No link found in the README to fix.
> Fixes #1264 - Find and fix link for Assessment 9 objectives

- data-visualization/data-visualization.md
**Closes Issue #1110**- Revise Check for Understanding section in data visualization
1. Following CFU guide #700, re-write questions with topics covered in this section
2. Revise "Let's Make a Bar Chart" section. _NOTE: Most of suggested changes in [#1086](https://github.com/Techtonica/curriculum/issues/1086#issuecomment-567664466) where solved in #1107)_ 
**In addition**
Unify punctuation marks for every paragraph in data visualization section
> fix: update data visualization section

- algorithms/sorting.md
> Changed code into JS

- career/interviewing/technical-interviewing.md
Fixes #1298 
- Added commonly asked short technical interview questions.
> added common technical interview questions

- command-line/command-line-interface.md
- javascript/javascript-9-async.md
- sass/sass.md
- web/jquery.md
fixes #1115
replaced 4 links with a free online resource.
> Replaced 4 Codecademy Pro links with a free online resource

- javascript/eslint.md
1. Proofread these two files for spelling and markdown:
javascript/eslint.md
linting/code-linting-eslint.md
(And these two files are merged into one file.)
2. Complete @vegetabill's requests made in this review: 
(https://github.com/Techtonica/curriculum/pull/1244/files)
3. Change the titles of the two files to be more relevant.
I have done all these given tasks.
Resolves #1279.
> Proofread javascript/eslint.md

- README.md
Closes #1282 
1. Fixed broken links
2. Changed the text **Resources: Women in Tech** to **Resources: Underrepresented in Tech** under Week 14 - Project Prep Week & Electives
Please review the changes and let me know if there is anything I need to add/change.
> Fixed links in README.md (#1282)

- web/BEM-style.md
closes #1240 
fixed typos and double checked BEM
> fixes issue #1240:Double-check BEM & md syntax, fix typos & wording in outline 

- javascript/eslint.md
address #1198 
Based on the changes made in resolving issue #1197 , the necessary changes have been made to their respective slides .Making a PR with a single typo fix as instructed on the issue.
> Correction of slides: issue 1198

- node-js/node-js.md
Added a node.js fundamentals study link
> Add node.js fundamentals study link

- react-js/react.md
1 link fixed, 1 typo corrected, report on dead links in issue comments
Closes #1122
> Closes #1122

- oauth/o-auth.md
Closes #1329 
- Added the given auth0 article under Supplemental Materials
> Added auth0 article

- workplace/Living in Open Workspaces.md
> Create Living in Open Workspaces.md

- career/working-and-collaborating-remotely.md
Resolves #1295 from the Hackathon
Previous PR was #1321 
Replacing with this PR due to some git issues
Review ended with revising the "Challenges" section with something more explicit and shorter.
> New lesson: Career - Working and Collaborating Remotely

- react-js/react-components-and-hierarchies.md
Solved #1336 : React Part 3 - Components & Hierarchies
> Created react-components-and-hierarchies.md

- react-js/react-part-2.md
This PR rectifies issue #1359 
Grammatical errors were also modified.
> Line 81 rectified and grammatical mistakes cleared

- web/html-forms.md
Fix #1343 
Form attributes added
> Add lesson on HTML forms

- javascript/Spread_operator.md
> adds the Spread-Operator file

- web/html-forms.md
Added a few resource links in Independent Practice.
Fixed issue: #1364
> Updated html-forms.md

- javascript/javascript-7-oop.md
Fixes #1269 
Changes proposed:
- Added benefits of OOP, a brief introduction
- Included resources for various concepts
Concepts covered:
- Introduction to functional programming
- Importance of OOP
- SOLID principles
- JS frameworks
@alodahl @Kundan28 Please review and merge this PR. Thank you.
> Added benefits of OOP in JS - #1269 resolved

- javascript/JavaScript-React-Modularity.md
- javascript/React_JavaScript.md
fixes #1320 
Please review the PR? @alodahl  @Aayush-1999  @Kundan28
> Adds the React file

- databases/relational-databases.md
I have completed all the items in the checklist except "**Remove LucidChart database example and links**" as I was not sure about it. So, I request you to review this and let me know about the LucidChart.
Closes #1380
> Remove unnecessary steps in the relational DB lesson #1380

- package-lock.json
- react-js/styling-react.md
> Update Styling in React Slides

- package-lock.json
- package.json
Can validators help me ensure that I didn't break husky?  I'm not sure how to test it.
- Nevermind, I think I got it.
> chore(packages): audit fix, list husky only once

- deploying/deploying-to-heroku.md
> Add thislinda

- deploying/deploying-to-heroku.md
With respect to the 2nd to-do, I added links to what seemed relevant/similar and helpful. But going through the steps myself, I couldn't figure out if the React/frontend part of the app was used at all, so that might affect how helpful some links are.
resolves #1403
> fix problems in heroku deployment docs (part 1)

- deploying/deploying-to-heroku.md
> fix problems in heroku deployment docs (part 2)

- projects/node-http-exercise/node-http-exercise.md
- projects/node-http-exercise/node-http-server-assignment.postman_collection.json
This Fixes #1187 
Created the assignment and the tests within a `node-http-exercise` folder in the `projects` folder.
The assignment is a markdown file and the tests file is in `json` format, to be imported in Postman.
Included in this PR is a `zip` file containing the solution and the test file.
```
node-http-exercise-solution.js
node-http-server-assignment.postman_collection.json
```
[node-http-exercise-solution-and-tests.zip](https://github.com/Techtonica/curriculum/files/5386832/node-http-exercise-solution-and-tests.zip)
Let me know if you need any changes, and I can't wait to contribute to other issues!
> Create Node HTTP server exercise without Express

- deploying/deploying-to-heroku.md
> Added a link to Node.js download and fixed a typo on commit statement

- career/roles-in-tech/security.md
Fix dead links. 
Addresses #1332
> Fix dead links

- api/REST-API.md
> fix: error in the Guided Practice section of the REST-API lesson

- career/roles-in-tech/security.md
To close the issue #1332.
Most links were already fixed. 
https://www.cloudflare.com/learning/security/glossary/what-is-penetration-testing/ is live, but will continue to fail validation due to blocking programmatic access.
> Fix dead and incorrect links

- projects/eventonica/README.md
Fixes #1417 
- Centralize project reqs here
- Remove Ticketmaster API reference
- Cut sequence details from end
> [Eventonica] Revise project intro README to cover simplified reqs

- security/web-security.md
> Fixed projected timelines web-security.md

- projects/eventonica/README.md
- projects/eventonica/eventonica-part1-objects.md
Fixes #1420 
Revise to meet new reqs and since we're trying to teach OO with this lesson, actually make a sensible OO skeleton.
> Revise Eventonica Part 1 to match new requirements

- dev-tools/dot-profile.md
This resolves ambiguity about where to put the copied line
> Clarify instruction for hello_world script

- web/accessibility.md
* Changed headline from A11y to accessibility
* Added new exercises and video demonstrations
* Added links from updated slide show
> Updating ADA curriculum

- solving-coding-challenges/solving-coding-challenges.md
Following step needed one more break to match format.
> Correct unmatched formatting

- README.md
- objectives/6.md
- projects/eventonica/README.md
- projects/eventonica/eventonica-part3-react.md
- projects/eventonica/eventonica-part4-apis.md
- projects/eventonica/eventonica-part6-postgres.md
- projects/eventonica/eventonica-part7-testing.md
- projects/mern-pern-project.md
See epic #1296
We have been working on Eventonica changes directly on the main branch which has left things in a weird state for those trying to map out the schedule and link to resources.
This PR does all the renaming and reordering specified so that links will work even if the revisions aren't fully complete yet and notes which are not yet done for increased visibility.
> Update Eventonica/README to match the current state

- git/github-collaboration.md
a fix for the issue mentioned here: https://github.com/Techtonica/curriculum/pull/1458
> fix: clarify add remote directions

- javascript/javascript-9-async.md
colors make code easier to read
> Add syntax highlighting to js-9-async

- api/intro-to-http.md
The Challenge was very confusing as the regular way to access user.agent is through the window object => window.navigator.user-agent but this window object only exists in the browser and not server side node.  I was able to find this code in a gist that was able to be used 
https://gist.github.com/ninjascribble/5119003
> Challenge section was a bit confusing

- testing-and-tdd/jasmine-testing.md
I added an indent where the solution should still be hidden in the details since right now it is half exposed
> Part of the solution is not hidden in details #9

- objectives/week-6-assessment.md
> syntax highlighting

- testing-and-tdd/jasmine-testing.md
import your `fizzBuzz` function into the spec file for the check your work section in number 5)
> import your `fizzBuzz` function into spec solution

- databases/database-intro.md
Added a link to the [Intro to Databases slides](https://docs.google.com/presentation/d/1oMn7IsFa5wf5aGcdsGf8ba3NdydYRO091maTJLxTb_E)
> Add link to Intro to Databases slides and update estimated time

- api/apis-and-json.md
> add syntax highlighting to apis-and-json.md

- react-js/styling-react.md
> Format React styling lesson code examples. 

- projects/eventonica/README.md
- projects/eventonica/eventonica-part2-testing.md
- projects/eventonica/eventonica-part8-api-testing.md
This addresses https://github.com/Techtonica/curriculum/issues/1215
- Added an API testing exercise using supertest and jasmine
- Edited prior testing exercise to include a script in `package.json` - this was part of the assignment but it made sense to include it with the prior exercise's Jasmine setup
> Eventonica API testing exercise

- api/REST-API.md
Many of us got confused on how these routes were deleting /posting/putting not realizing it was psuedo code.
> Add a comment how there is psuedo code

- react-js/react-part-1-intro.md
for second resource change 5 min video to 5 min article (it is not a video)
> Update video to article

- api/intro-to-http.md
blogs were made by a Techtonica volunteer, Dave Dash
> added an overview of servers, req, and res

- react-js/react-hooks.md
Added JS syntax highlighting to the code blocks, for better readability
> Add JS highlighting to react-hooks.md

- react-js/react-part-3-component-hierarchies.md
i think the update function was left over c/p from the parent component and doesn't belong there
> removed update function in child component

- projects/eventonica/eventonica-part7-react.md
Originally opened as #1472 but I messed up that branch in Git 😬 
- include specific walkthrough of porting JS DOM code => React
- Link to other new content since originally created
- Keep all server / API hints
> [Eventonica React] - merge existing content with additional porting instructions

- react-js/react-part4-full-apps.md
I believe we actually had 2 todos (1) Walk Dog (2) feed cat
> One todo -> two to do

- projects/mailing-list-rest-api.md
for clearer instruction, similar to what was in REST API  guided practice lesson
> Also added a line about psuedo code

- node-js/node-js.md
The lab exercise has us running node javascript code in our command line. Since we used the command line we did not use or create an app.js file. In the exercise we did not create a basic web app using Node.
> The lab exercises

- refactoring/refactoring.md
> add syntax highlighting

- react-js/react-part-2-component-state.md
1. It was really hard to understand if 1. was saying what the misconception was or if this was the correct way to think about it. I added correct at the front to follow the format and specify that this is the right way to think about things.
2.Added spacing and indentations to Common Mistakes 1. it was really hard to understand what was going on.
> Common Mistakes 1

- databases/sql-1.md
Since we have been learning the importance of including a primary key in our table I updated the independent practice to include a primary key column
> add id as primary key for independent practice

- projects/recipe-page/phase-1-html-prompt.md
- projects/recipe-page/phase-2-css-prompt.md
- react-js/react-part-1-intro.md
- web/css-part-2.md
- web/css.md
- web/html-forms.md
- web/html.md
- web/js-dom-methods.md
- web/media-queries.md
(In progress): Updates for H2 discussed between @SarahCawley and I based on current trends & participant feedback:
- no longer require bootstrap
- slow down & break up css outline
- more basic css practice
- more basic html practice
- don't require CLI or VSCode until after HTML & CSS intros
> feat(html,css,js-dom): curr updates: no bootstrap, more css & html practice

- javascript/javascript-7-oop.md
Removed incorrect video walk through link for tutorial JavaScript 7
> Removed incorrect video walk through link for tutorial JavaScript 7

- career/working-and-collaborating-remotely.md
Update the survey link to the 2021 report that discusses pre- and post-pandemic changes and comparisons
> Update remote work survey link

- projects/full-stack-checklist.md
Initial pass at creating a full stack PERN app checklist - linked issue https://github.com/Techtonica/curriculum/issues/1287
TODO: final test of all instructions
> WIP PERN checklist

- git/github-storage.md
The original lesson dives directly into creating repos on Github, etc. It would be nice to have the setup and configurations of Git and Github ready before actually interacting with the terminal.
> Add git/github configurations

- web/js-dom-methods.md
I'm also adding a different option of tutorial besides the TreeHouse tutorial
> Update links for Bubbling and Propagation

- onboarding/professionalism.md
Removed "Guidelines for Women" and changed to simply be a part of the larger professional dress section.
> Edit to Change Gendered Language

- dev-tools/vscode.md
Update the link to prerequisite lesson
> Update dead link

- javascript/javascript-4-loops.md
> Changed 'be used' to 'is used'

- onboarding/tech-industry-tips.md
Change 'acccount' to 'account' in line 21 about emails
> Update spelling error in line 21

- networking-computing/README.md
Change misspelling of "receiptionist" to "receptionist"
> Correct misspelling on line 22

- api/REST-API.md
I and some other participants were unclear on where to include the following steps of code; whether it be in the terminal or code editor. 
Instead of *Create a new file `server.js` and inside, follow these steps:" change it to "Create a new file named `server.js` with your favorite editor and inside, follow these steps:"
> Add more clarity for instructions in line 197

- command-line/env.md
Change 'exports.I_LOVE = process.env.I_LOVE;' to ES6 version to 'export const I_LOVE = process.env.I_LOVE;'
> Update JavaSript in line 137 to ES6 JavaScript

- projects/eventonica-react/eventonica-react-part-2.md
- projects/eventonica-react/eventonica-react-ui.md
- projects/eventonica-react/starter-code/starter-jsx.js
Revamp the Eventonica Project to use React
In this lesson, participants will:
Create a Users component with:
- A list using a mock list of user objects
- A simple form to create a user with an ID, name and email (and other fields if they'd like)
- A DeleteUser component that will delete a user from the list
This will be followed up by part 2 (outline included). Part 2 will be a more advanced react lesson, and will introduce useReducer, useEffect, and possibly some other react concepts, depending on timing
- the starter code is adjusted a bit to format the inline instructions as comments, and move the `user` section before the `events` section, since participants will work on the User flow first.
> Eventonica React Lesson Pt 1

- package-lock.json
- package.json
Skips domains that are guaranteed to fail by traffic detection or are local addresses
168 warnings
56 warnings with change
Related to  #1437 
```md
agile-development/intro-to-agile.md
124:3-124:141  warning  Link to https://www.gp-training.net/training/communication_skills/consultation/equipoise/complexity/stacey.htm is dead                                  no-dead-urls  remark-lint
algorithms/sorting.md
16:441-16:522  warning  Link to https://dev.to/cooperfle/whats-the-point-of-learning-how-to-sort-20dl is dead                                                                   no-dead-urls  remark-lint
best-practice-in-development/best-practice-in-client-side-development.md
39:3-39:110  warning  Link to https://www.belatrixsf.com/blog/best-practices-for-front-end-coding/ is dead …
```
> Reduce remark false positives by skipping guaranteed failures

- datetime/datetime.md
This lesson file was outdated when we covered it, so I added another option
> Add link + info to Temporal JS Date/Time API

- databases/installing-postgresql.md
update the installation process of postgres
> Install psql

- databases/install-postgres-with-docker.md
This file contain installation of psql using docker. In 2021 H2 cohort was following a medium article which had some minor errors, and costed all the members a day to get postgres installation working. Based on the same article I created this section and it worked.
> create psql-docker file

- README.md
Adding the docker lessons to the db week!
> Update the Databases week!

- project-example/week-9/eventonica/README.md
- projects/js-html-games.md
- projects/mern-pern-project.md
- projects/portfolio/portfolio-webpage-1.md
- projects/portfolio/portfolio-webpage-2.md
- projects/portfolio/portfolio-webpage-3.md
- projects/react-game.md
- projects/recipe-page/phase-1-html-prompt.md
- projects/recipe-page/phase-2-css-prompt.md
- projects/recipe-page/phase-4-DOM-Manipulation.md
- projects/rest-api-project.md
Added FAQs section to weekly project
> Frequently Asked Questions

- practice/participants.md
Added my name in practice file for 2022 H2
> add new name

- practice/participants.md
adding sophia name to participants file
> sophia-pung

- projects/week-1-worksheet.md
For someone who isn't familiar with the shell it can be a bit tricky to even know what to google when someone says "add an alias."
Also these days macOS actually uses Zsh by default and not bash so people may get conflicting information if they google how to do things in bash when really they are using zsh. In particular these two shells have different rc file names!
Just added some resources to give people a better starting point before going off of the google deep end wasting time on the first resource they find even if it is about something completely different or has misleading information.
> Augment shell worksheet

- projects/rest-api-project.md
Adding more clear instructions, links to examples of code working and resources
> Update rest-api project

- coding-interviews/readme.md
Many questions during Josh Goldberg's interview session! I've answered a few in line and then redirected to some webpages for further information.
> Add section on coding interviews

- code-challenges/string.md
Hi!
My name is Chaithanya. I recently started to learn coding and I'm new to GitHub. This is my first ever pull request.
I noticed that this repo is for beginners and I thought of contributing.
I registered as a volunteer in "Techtonica Volunteer Application". 
I created a few test cases and a sample solution for the first problem in "string.md"
I hope this is what you are expecting from the contributors. If you like it, please let me know and I will continue to contribute.
Thanks for taking time to my contribution.
> Test Cases and Sample Solution is added

- onboarding/learning-to-learn.md
Proofreading for spelling, grammar, and readability
> Proofreading Learning to Learn

- dev-tools/command-line-interface.md
-Proofreads for spelling, grammar, and readability
-Adds note about why commands sometimes start with $ (so newbies don't think it's part of the command and think their Terminal is broken, like I did)
> Proofreading and Adding to Command Line Interface

- code-challenges/arrays.md
Completed the test cases and sample solution for problem one. I would like feedback on the sample solution, if it looks good, I will go ahead and do similar to the rest of the solutions.
> #1941 incomplete resources for array code challenges

- onboarding/professionalism.md
Proofreading for grammar, spelling, and readability
Note: "Behaving professionally demonstrates that you value your role, your team, and your employer and are conscientious." is repeated in 2 different parts of the "Common Mistakes / Misconceptions" section
> Proofreading Professionalism

- code-challenges/Objects.md
This changes resolves Issue #1944 by adding the sample solution along with the testcases and output in the Objects.md file.
I would request you to please have a look into it.
Regards,
Akshay
> Incomplete resources for code challenges using Objects Literals in JS

- code-challenges/arrays.md
Code challenges resource complete. Each problem has 3 test cases and  a sample solution
> #1941: Incomplete Resouces for Array Code Challenges

- dev-tools/keyboard-shortcuts.md
Note: I would add somewhere in the curriculum that "command + /" comments/uncomments code and that highlighting code then doing tab or shift + tab will indent or negatively indent respectively. It's very useful, and I wish I'd learned it before my first HTML project. However, I don't think this file is the right place for that.
> Proofreading Keyboard Shortcuts

- git/git-version-control.md
Note: May also be good to mention Git GUIs in here. We didn't know about them until way later, so most of us had already gotten used to the Terminal
> Proofreading Git Version Control

- dev-tools/vscode.md
Proofreads and adds a line about the commenting/uncommenting code shortcut
> Proofreading + Editing VS Code

- code-challenges/string.md
> Added solutions to strings problems

- code-challenges/arrays.md
- Updated Formatting for additional problems added
- Fixed bugs for problems 10 and 16
> fix(arrs): updated formatting for additional problems and fixed bugs

- api/intro-to-http.md
- career/resume-writing.md
- career/roles-in-tech/data-science.md
- career/roles-in-tech/developer-advocate.md
- career/roles-in-tech/product-manager.md
- career/roles-in-tech/qa.md
- career/roles-in-tech/sales-engineering.md
- career/roles-in-tech/technical-program-manager.md
- career/roles-in-tech/technical-writing.md
- chrome-developer-tools/chrome-developer-tools.md
- coding-interviews/readme.md
- debugging/debugging.md
- electives/oauth/o-auth.md
- express-js/express.md
- git/git-version-control.md
- node-js/node-js.md
- react-js/react-part-5-full-apps.md
- recursion/recursion.md
- testing-and-tdd/jest.md
- testing-and-tdd/testing-and-tdd.md
- testing-and-tdd/testing-mindset.md
Add links to recorded talks to the supplemental materials about specific roles in tech and technical topics.
Testing Notes: 
- click each link and ensure it goes to appropriate video
> Add video links to relevant curriculum READMEs

- career/difficult-workplace-situations.md
- career/linkedin.md
Add links to recorded talks to the supplemental materials about resume & LinkedIn topics.
Testing Notes:
- click each link and ensure it goes to appropriate video
> Add more videos to relevant GitHub lessons

- dev-tools/command-line-advanced.md
- reading-and-writing-documentation/documentation.md
- web/media-queries.md
- writing-readable-code/writing-readable-code.md
Update some grammar and resource references.
> Update curriculum for week 2

- README.md
- package.json
- pair-programming/week-6/expressjs-router/about.html
> Omit "free" references.

- giving-presentations/giving-presentations.md
- javascript/javascript-4-loops.md
- javascript/javascript-7-oop.md
- javascript/restaurant recommender/RestaurantRecommender - part1.md
- projects/portfolio/portfolio-webpage-1.md
- projects/portfolio/portfolio-webpage-2.md
- projects/portfolio/portfolio-webpage-3.md
- projects/recipe-page/phase-4-DOM-Manipulation.md
- underrepresented-in-tech-resources/resources-adhd.md
- writing-readable-code/writing-readable-code.md
Added grammar and typo fixes to a few files.
> updated grammar and some typos

- projects/pern-contact-list-app.md
- projects/pern-game-app.md
- projects/pern-weather-app.md
I copied week 11 projects instructions from Cristina's github.
> Week 11 project ideas

- projects/react-game.md
Rephrased the statement about BMI calculator
> BMI calculator statement rephrased

- pair-programming/week-5/react-couter-app/README.md
Updated the README for the week 5 counter-app exercise to allow participants more flexibility in link submissions. Added options for submitting links from Replit, GitHub, and CodePen, in addition to CodeSandbox, to accommodate different preferences and address recent CodeSandbox limitations.
> Added more options for link submission of counter-app-exercise in week 5

- projects/week8GameREADME.md
Added new project requirements for users to customize the trivia game by selecting the number of questions, question type, difficulty, and category.
> Added clear project requirements for week 8 game.

- onboarding/learning-to-learn.md
- testing-and-tdd/vitest.md
Added a `vitest` testing lesson for participants working with React + Vite applications, including setup, running tests, test coverage, and writing basic assertions.
> Created and added vitest to testing lessons.

- practice/project_collaboration.md
Added a lesson for participants on collaborative project work, focusing on team coordination and Git practices. Participants will revisit a previous project and develop a new Animal Sighting Tracker app together, managing tasks, incremental deadlines, and daily check-ins to enhance teamwork.
> Created a topic outline for participants to experience "Project Collaboration with Multiple Contributors"

- README.md
i wrote some things and pushed it up
> Audit Projects for Weeks 12, 13, 14, & 15

- projects/js-html-games.md
- projects/react-game.md
This is a PR for issue #2114 : Auditing the projects in Week 4 & 5 and implementing minor changes to the projects instructions for understanding and clarity. 
In Week 4, I added text to clarify the Github deployment extension item as it read a bit clunky. I also changed the header to "Optional Extension" to stay consistent.
In Week 5, I added some context to the linked example problem as they are from an outdated version of React. I noted this and also added a link for the new React documentation as well as a Tic-Tac-Toe tutorial from React.
The rest of the content in both weeks feels clear, is readable, and leaves a lot of room for creativity when choosing a game to build.
> Audit - Game Projects Weeks 4 & 5

- projects/recipe-page/phase-4-DOM-Manipulation.md
I have made the following changes to the week 2 project outline and attached a screenshot taken prior to making changes:
- fixes spelling typo in the title (method → methods)
- fixes punctuation typos under Languages section
- removes JS from overview section (students will be incorporating JS in this phase of the project)
> Issue #2113 - Audit week 1 and 2 projects

- electives/sass.md
- javascript/javascript-1-variables.md
- javascript/javascript-2-array-functions.md
- javascript/newer-JS-features.md
- javascript/week-4-JS-assessment.md
- meta/false-dead-links.md
- objectives/7.md
- onboarding/asking-good-questions.md
- operating-systems/hardening.md
- personal-brand/personal-branding.md
- prework/prework.md
- program-prep/ethics.md
- program-prep/underrepresented-in-tech.md
- project-example/week-9/eventonica/eventonica-express-backend.md
- project-example/week-9/eventonica/eventonica-postgres.md
- projects/eventonica-legacy/eventonica-part5-express-backend.md
- testing-and-tdd/vitest.md
- ui-ux-design/ui-ux-design.md
- underrepresented-in-tech-resources/underrepresented-in-tech-India.md
- web/bootstrap.md
- web/css-part-2.md
- web/html.md
Second pass at implementing the changes which include updating or removing links that were flagged as dead.
I have added false dead links to the false-dead-link.md after checking that each flagged resource still has relevant content.
> [Part 2] Adjustments to Repo After Running Dead Link Checker

- meta/false-dead-links.md
- projects/data-structures-algorithms-sprint.md
- projects/final-project/selecting-your-project.md
- react-js/class-based-components/react-part-1-intro.md
- runtime-complexity/runtime-complexity.md
- security/web-security.md
- testing-and-tdd/enzyme-testing.md
- testing-and-tdd/react-testing-jest-and-RTL.md
- testing-and-tdd/testing-and-tdd.md
Third pass at implementing the changes which include updating or removing links that were flagged as dead.
I have added false dead links to the false-dead-link.md after checking that each flagged resource still has relevant content.
> [Part 3] Adjustments to Repo After Running Dead Link Checker 

- api/REST-API.md
- data-structures/linked-lists.md
- data-structures/queues.md
- projects/2023TemplateWithVite/README.md
- projects/final-project/planning-your-project.md
- projects/minimal-api-project.md
- projects/node-http-exercise/node-http-exercise.md
- projects/recipe-page/phase-1-html-prompt.md
- projects/rest-api-project.md
- projects/take-home-problems/backend.md
- projects/week8GameREADME.md
This PR ensures all supplemental material links are updated with the appropriate media type descriptions for better clarity and accessibility. For example:  
- **How to Dump and Restore PostgreSQL Database? (Article)**  
The following project files were reviewed and updated:  
- **2023 Template With Vite**  
- Blog App  
- Contact App  
- Eventful API Test Page  
- Eventonica (Legacy Version & Updated Version)  
- Final Project  
- Node HTTP Exercise  
- Portfolio  
- Recipe Page  
- Take-Home Problems  
- Advanced Methods Assessment  
- Auth0 Assessment  
- Data Structures and Algorithms Assessment  
- Data Structures and Algorithms Sprint  
- Database Modeling Assignment  
- Full-Stack Assessment  
- Full-Stack Checklist  
- JavaScript & HTML Games  
- Kickball Signups Project  
- …
> Ensure Links to Project Resources Are Clear with Media Type Descriptions (Ticket #2090)  

- projects/eventonica-updated/README.md
- projects/mern-pern-project.md
Issue: audit, report, and implement needed changes to the curriculum for areas of the existing full time program projects that aren't clear. This audit was for week 9: [Eventonica](https://github.com/Techtonica/curriculum/tree/main/projects/eventonica-updated), and week 10: [Animal Sighting App](https://github.com/Techtonica/curriculum/blob/main/projects/mern-pern-project.md).
Feedback request: to check if changes I made are in line with what is wanted out of these audits and that I am following PR etiquette correctly.
I have completed the following changes:
> Audit of weeks 9 and 10

- open-source/open-source.md
Finish the opensource lesson in our curriculum with special attention to problems described in issue #2151
> Finish opensource lesson to resolve #2151

- projects/pern-contact-list-app.md
- projects/pern-game-app.md
- projects/pern-weather-app.md
- projects/weather-app.md
- projects/week8GameREADME.md
This PR includes various improvements across multiple projects, focusing on adding resources, fixing grammatical issues, and enhancing documentation. The following files were audited:
- [Weather App](https://github.com/Techtonica/curriculum/blob/main/projects/weather-app.md) (i.e. weather-app.md)
- [Quiz App](https://github.com/Techtonica/curriculum/blob/main/projects/week8GameREADME.md) (i.e. week8GameREADME.md)
- [Contact App](https://github.com/Techtonica/curriculum/blob/main/projects/pern-contact-list-app.md) (i.e. pern-contact-list-app.md)
- [Weather2](https://github.com/Techtonica/curriculum/blob/main/projects/pern-weather-app.md) (i.e. pern-weather-app.md) -or- [Game2](https://github.com/Techtonica/curriculum/blob/main/projects/pern-game-app.md) (i.e. pern-game-app.md)
- Added …
> Curriculum Improvements: Grammar, Styling, and Resources for Weeks 7, 8, & 11 (#2116)

- practice/participants.md
- practice/pull-request-review-practice.md
This pull request addresses Issue #2069 by creating a detailed outline for cohort activities aimed at practicing the pull request (PR) review process.
Activity Design:
- Created two interactive activities to help participants learn how to:
- Create high-quality pull requests with proper titles, descriptions, and visuals.
- Review pull requests effectively and provide actionable feedback.
- Incorporated collaborative tasks to simulate real-world workflows, such as commenting on code and addressing feedback.
Integration with Week 8 Curriculum:
- Aligned the activities with participants' concurrent project of building a game application that fetches API data.
- Included references to time management, work breakdown, and accountability practices.
Lesson Plan Structure:
- Added sections like …
> Resolving Issue #2069 - Creating Topic Outline for PR Review Practice Week 8

- projects/blog-app/README.md
- projects/final-project/README.md
- projects/final-project/planning-your-project.md
This is a PR for issue https://github.com/Techtonica/curriculum/issues/2117 : Auditing the projects in the Blog App Project and the Final Project in Week 12-15 and implementing minor changes to the projects instructions for understanding and clarity.
I made some minor adjustments for readability in the Blog App instructions, like the 4th bullet in this list clarifying 4 total fields are necessary to get full points, 2 required and 2 non-required fields.  
In the Final Project instructions, I again just made a few adjustments, like making it clear a total of 50 commits was required for the project and to use the week 1-4 milestones in planning their schedule.
> Audit - Projects Week 12-15 Issue #2117

- react-js/react-part-1-intro.md
- react-js/react-part-2-props.md
- react-js/react-part-3-state.md
Page where problem found?
https://github.com/Techtonica/curriculum/tree/main/react-js
Type of problem
Outdated content
Suggested Solution
This content should be updated to reflect the current state of the React Documentation, the new documentation is well written and includes the changes to React 19.
Updated links that pointed to legacy react docs to the new react docs for react-part-1, react-part-2, and react-part-3.
> Updated React Docs

- career/career-exploration.md
Add a career exploration topic outline to the careers folder.
New topic outline to aid target audience in exploring their career paths.
- Issue Number: #2287
- Explains the purpose of career explorations
- Considerate of target population: women and non-binary adults career changing into full stack software engineering or tech adjacent roles
Read through the topic outline and ensure it reads seamlessly and with empowerment
- No table of contents updates needed.
- This creates an additional file in the career folder
- At present the FT program does not explore this in the curriculum schedule, this would be ideal to introduce during weeks 10+ during pair programming
> [Issue 2287] Career exploration topic outline

- react-js/advanced-routing-navigation.md
Add a advanced routing navigation topic outline to the reactjs folder.
The following concepts are discussed and in depth interactive activities are provided:
- Setting up and configuring React Router v6
- Working with dynamic route parameters and nested routes
- Implementing layouts and shared UI components across routes
- Creating protected routes with authentication
- Managing navigation state and history
- Implementing error boundaries for routes
- Code-splitting and lazy loading routes
- Handling route transitions and animations
- Programmatic navigation techniques
- Testing routing components
- Issue Number: #2281
- Explains advanced routing and navigation concepts
- Considerate of target population: women and non-binary adults career continuing their learning …
> [Issue 2281] Advanced routing navigation

- react-js/react-routing-forms.md
Add a react routing for forms topic outline to the reactjs folder.
The following concepts are discussed and in depth interactive activities are provided:
- Configure client-side routing in a React application using React Router
- Create multi-page React applications with consistent navigation
- Implement form handling and data collection in React
- Validate user input and display appropriate feedback
- Use URL parameters to create dynamic routes
- Connect routing with form data to create a complete user flow
- Issue Number: #2280
- Explains the purpose of react routing with forms
- Considerate of target population: women and non-binary adults career continuing their learning journey into more advanced full stack software engineering concepts
Read through the topic …
> [Issue 2280] Create react-routing-forms.md

- best-practice-in-development/rendering-approaches-web-development.md
- networking-computing/rendering-approaches-web-development.md
Create comprehensive educational outline covering Server-Side Rendering and Static Site Generation fundamentals. 
Includes 4 hands-on activities:
- Understanding rendering approaches comparison
- Building SSR with Express and React
- Implementing SSG and hybrid approaches
- Performance analysis with real-world blog implementation
Content designed for accessibility without bundlers, using vanilla JS for client-side interactivity.
- Issue Number: #2282 
- Explains the purpose of Server-Side Rendering (SSR), Client-Side Rendering (CSR), and Static Site Generation (SSG)
- Considerate of target population: women and non-binary adults career continuing their learning journey into more advanced full stack software engineering concepts
Read through the topic outline and ensure …
> [Issue 2282] Add SSR/SSG curriculum with interactive activities

- README.md
- machine-learning-systems-generative-ai-models/README.md
Introductory README and new folder to house ML/LLM/AI related topic outlines
Detail what changes this pull request has and to which areas of the codebase.
Issue Number: 2328
New folder and README
- Ensure that technical terms unfamiliar to non-technical readers can understand the content and do not identify the reading as jargon
- The README must clearly articulate the current industry debate on tech education relevancy, distinguish how entry-level career changers compare to AI tools, and emphasize the business importance of understanding modern AI technologies, all in accessible language suitable for career-changing professionals.
- **Industry validation** - review if the content accurately reflects current industry expectations
- **Readability check** - ensure content is accessible (aim …
> [Issue 2328] Create README.md and ML/AI root folder

- machine-learning-systems-generative-ai-models/ai-tooling.md
- machine-learning-systems-generative-ai-models/intro-to-ai-tooling.md
This PR updates the AI Tooling Curriculum to emphasize collaborative learning with AI tools rather than copy-paste approaches. It adds new visual guides, interactive components, and restructures the content to promote critical thinking and understanding when using AI coding assistants.
1. **Updated Example Prompts**: Revised prompting examples to focus on understanding, reasoning, and collaborative problem-solving rather than solution generation
2. **Added New Section**: "AI as a thought partner, not a replacement" to explicitly teach collaborative AI usage
3. **Created Visual Guides**:
1. Pair Programming with AI Guide showing a 5-step collaborative workflow
2. Student Reflection Prompts with categorized effective prompting templates
3. Before/After Examples showing ineffective vs. …
> [Issue 2330] Create “AI Tooling” topic outline

- algorithms/searching.md
This PR expands the existing Searching Algorithms topic with comprehensive explanations and interactive walkthroughs for Linear and Binary Search algorithms. The current content was minimal, briefly discussing linear and binary search with resources pointing to DFS and BFS concepts. This update provides a more thorough educational resource with visual explanations, code implementations, and practice exercises.
- Added detailed explanations of Linear Search and Binary Search algorithms
- Created visual step-by-step walkthroughs for both algorithms
- Added JavaScript implementations with explanations
- Included time and space complexity analysis for both algorithms
- Added comparison table between Linear and Binary Search
- Included real-world applications section
- Created guided practice …
> [Issue 2247] Update searching.md

- algorithms/approximation-algorithms.md
This PR adds a comprehensive topic outline on Approximation Algorithms. The outline follows the curriculum structure with prerequisites, objectives, detailed learning content, self-guided activities, and common misconceptions.
- Added a new topic outline on Approximation Algorithms
- Included detailed explanations of approximation algorithm concepts with JavaScript examples
- Created four self-guided activities with estimated completion times
- Provided real-world applications and examples
- Added common mistakes/misconceptions section
- Included a table of contents with hyperlinks to each section
- Referenced appropriate prerequisites from the Techtonica curriculum
Issue Number: #2274
- Topic outline follows the required structure (prerequisites, TOC, objectives, …
> [Issue 2274] Create approximation-algorithms.md

- electives/progressive-web-apps-and-service-workers.md
This PR adds a comprehensive topic outline for Progressive Web Apps (PWAs), service workers, and PWA development to the curriculum.
- Added a new markdown file `pwa-topic-outline.md` with the following sections:
- Prerequisites with links to existing Techtonica curriculum
- Table of contents with hyperlinks to each section
- Clear learning objectives
- Detailed "Specific Things to Learn" section with real-world examples, benefits, and tradeoffs
- Four self-guided activities focused on implementing offline functionality, building a PWA, testing/debugging, and performance optimization
- Common mistakes and misconceptions section
- Additional resources for further learning
Issue Number: #2279
- Topic outline follows the standard Techtonica curriculum format
- Prerequisites …
> [Issue 2279] Create "Service Worker, PWA, and How to Build PWA" topic outline

- CONTRIBUTING.md
- projects/2023TemplateWithVite/client/src/components/ListStudents.jsx
- projects/eventonica-legacy/eventonica-part1-objects.md
- projects/eventonica-updated/README.md
- projects/final-project/README.md
- projects/js-html-games.md
- projects/minimal-api-project.md
- projects/node-http-exercise/node-http-exercise.md
- projects/recipe-page/phase-3-bootstrap-prompt.md
- projects/take-home-problems/frontend.md
- projects/week-1-worksheet.md
> chore: fix typos across codebase

- README.md
1. the links on the readme file have been tested and ensured they all lead to the appropriate pages
2. Some of the links dont direct to the pages they are supposed to be in,this branch has a clean readme file that has all the links checked on.
3. Issue #2362
4. Type of Change
- Bug fix
- Documentation update
5. How to test 
all links on the readme file should be click on to check the authenticity of the link
6.  Checklist
> readme file all cleaned up

- career/job-seeker.md
This PR introduces a comprehensive self-guided job search framework for our graduates. The outline provides structured guidance for individuals or self-formed collaborative groups to navigate the job search process effectively without requiring formal program participation. It transforms program-specific content into a self-directed resource with daily schedules, weekly focus areas, and curated resources.
- Created a markdown topic outline for self-guided job seekers
- Developed a flexible daily schedule template adaptable for individual or group use
- Organized technical and job search activities into weekly focus areas (20-week framework)
- Curated relevant resources for each topic area with links
- Added detailed breakdowns for key activities (code challenges, networking, applications, …
> [Issue 2350] Create job-seeker.md topic outline

- projects/recipe-page/phase-3-bootstrap-prompt.md
- web/bootstrap.md
This PR updates the Recipe Page Phase 3 and Bootstrap Topic Outline to improve clarity, add modern framework context, and make content easier for learners to digest
updated the Recipe Page Phase 3 and Bootstrap Topic Outline 
- Issue Number: 2368
- Documentation update
- Topic Outline
-  I have performed a self-review of my code.
-   My code follows the style guidelines of this project.
-  I have tested my code locally and verified the website is working as expected.
@daaimah123
> Improve Recipe Page Phase 3 and Bootstrap Topic

- program-prep/ethics.md
Add additional resource to the AI tooling lesson's activity on ethical considerations.
Issue Number: #2384
Topic Outline Update
> [Issue 2384] Add reference to the ai-ethics activity in the ethics.md

- onboarding/pair-programming.md
Add content about working across varied technical mastery levels and video resources.
Issue Number: #2392
Topic Outline Update
> [Issue 2392] Update How to Pair Topic Outline

- algorithms/divide-and-conquer.md
- **Complete lesson structure** with realistic time estimates (2.5-3 hours total)
- **Prerequisites section** linking to existing curriculum (recursion, Big O, arrays, functions)
- **Motivation section** connecting programming concepts to real-world experiences (project management, cooking, learning)
- **5 interactive activities** progressing from physical understanding to code implementation:
- Paper Folding Challenge (kinesthetic learning)
- Binary Search Detective (guided implementation)
- Merge Sort Visualization (step-by-step building)
- Real-World Problem Solving (application practice)
- Algorithm Race (performance comparison)
- **Learning objectives** focused on practical skills and understanding
- **Specific learning topics** covering concepts, algorithms, analysis, and …
> [Issue 2253] Create divide-and-conquer.md

- algorithms/longest-increasing-sequence.md
This PR adds a comprehensive lesson on the Longest Increasing Subsequence (LIS) algorithm to the CS curriculum. The lesson is designed for new developers with clear explanations, visualizations, and interactive activities to help solidify understanding of this important dynamic programming concept.
- Included time estimates for reading and activities
- Created prerequisite links to existing Techtonica curriculum
- Developed motivation section with real-world applications
- Designed clear learning objectives and specific concepts to learn
- Created 7 interactive activities with visualizations:
- Understanding subsequences
- Identifying increasing subsequences
- Brute force approach
- Dynamic programming solution with visualization
- Binary search optimization
- Reconstructing the actual …
> [Issue 2250] Create longest-increasing-sequence.md

- projects/portfolio/README.md
- projects/recipe-page/README.md
- web/bootstrap.md
This PR introduces introductory README.md files for both the Recipe and Portfolio project folders. Each README includes:
- Project overview and purpose
- Basic structure and file organization
- Setup or reference instructions if applicable
These additions aim to improve project clarity and accessibility for collaborators and reviewers.
- recipe/README.md — Added project description and file summary
- portfolio/README.md — Added overview and development notes
- Issue Number: #2367
- Documentation update
> README_ Creation

- react-js/class-based-components/react-part-1-intro.md
- react-js/class-based-components/react-part-2-component-state.md
Description:  
This pull request corrects spelling mistakes in the documentation for React class-based components. Specifically, it changes "reuseable" to "reusable" and "reconcilation" to "reconciliation" in the relevant markdown files. These changes improve the accuracy and professionalism of the documentation. No functional code changes are included.
> Fix Typos in React Class-Based Components Documentation

- javascript/javascript-maps-and-sets.md
1, Added the "Independent Practice" section.
2. Added the "Activities" section.
3. Made a tiny edit to the overall structure to correct hierarchy.
> [Issue 2381] Add practice and activities sections

- data-structures/graphs-depth-breadth-first-search.md
Comprehensive, beginner-friendly learning module covering Graphs, Breadth-First Search (BFS), and Depth-First Search (DFS) for new developers. Breaks down the "how" and "why" making concepts accessible, practical knowledge through real-world examples, interactive visualizations, and hands-on coding activities.
- 3.5 hours total activities
- **Graph Detective** - Recognize graphs in real applications (15 min)
- **Build Your First Graph** - Hands-on graph construction (20 min)
- **BFS Visualization Walkthrough** - Interactive algorithm animation (25 min)
- **DFS Deep Dive** - Recursive vs iterative exploration (25 min)
- **Algorithm Race** - Performance comparison tool (20 min)
- **Code Implementation Challenge** - Guided coding practice (45 min)
- **Real-World Problem Solving** - Applied …
> [Issue 2243] Create graphs-depth-breadth-first-search.md

- algorithms/fenwick-binary-indexed-tree.md
- Step-by-step visual explanations
- Three progressive activities
- Beginner-friendly explanations
- Visual tree representations
- Common pitfalls section
- Complexity analysis table
- Practice problems
Issue Number: #2268
> [Issue 2268] Create fenwick-binary-indexed-tree.md

- algorithms/articulation-points.md
The topic outline provides a comprehensive introduction to the concept, algorithm implementation, and practical applications of articulation points, which are critical nodes in a graph whose removal would disconnect the graph. Changes include:
- Clear time estimates for each section
- Prerequisites linked to existing curriculum
- Motivation section explaining real-world relevance
- Detailed objectives and learning outcomes
- Step-by-step algorithm walkthrough with visualizations
- Code implementation with explanations
- Interactive exercises with solutions in collapsible sections
- Practice problems of varied difficulty
- Real-world application examples
- Additional resources for further learning
Issue Number: #2269
> [Issue 2269] Create articulation-points.md

- career/roles-in-tech/management_roles/product-manager.md
- career/roles-in-tech/sales-engineering.md
**Description:**  
- Fixed minor typos and improved wording for clarity in the Product Manager and Sales Engineering role documents.
- No changes to content or structure; only text enhancements for better readability.
> Minor Text Improvements in Product Manager and Sales Engineering Roles

- web/js-dom-methods.md
This pull request addresses by updating the "JS HTML DOM Methods" topic outline. The core of this change is to provide crucial context about jQuery's role in the history of web development, clarify the distinction between jQuery and native DOM manipulation, and explain why jQuery is now considered outdated for most new projects. This update ensures that participants understand the modern landscape of JavaScript while learning foundational DOM manipulation skills.
The changes are focused on the `js-dom-methods.md` file and include:
1.  **Added a New Section: "A Note on jQuery vs. Vanilla JavaScript"**
*   This new H2 section was inserted to directly address the issue's concerns.
*   It defines what jQuery is (a wrapper library for JavaScript) and its primary purpose.
*   It provides …
> [Issue 2371] Reinforce DOM manipulation vs jQuery 

- README.md
1. Added the new section topic to the table of contents.
2. Added the actual section.
> [Issue 2383] Add core soft skills section

- projects/blog-app/README.md
- projects/contact-app/README.md
- projects/eventonica-updated/README.md
- projects/js-html-games.md
- projects/mern-pern-project.md
- projects/portfolio/README.md
- projects/react-game.md
- projects/recipe-page/README.md
- projects/rest-api-project.md
- projects/weather-app.md
- projects/week8GameREADME.md
Added / updated commit requirements to a minimum of 50 commits
Please include a summary of the changes and the related issues.
Some projects did not have commit requirement, and some had 15. These edits now will require 50 commits instead.
Detail what changes this pull request has and to which areas of the codebase.
All of the changes are only in the readme files. 
- Issue Number: #2320
- Documentation update
- Topic Outline
- Should tis week still have 50 commits? 
- Week 11. 2 mini projects in 1 week! [Contact List](https://github.com/Techtonica/curriculum/blob/main/projects/pern-contact-list-app.md) and choice of [Weather App](https://github.com/Techtonica/curriculum/blob/main/projects/pern-weather-app.md) or [Game App](https://github.com/Techtonica/curriculum/blob/main/projects/pern-ga …
> Commit changes 2320

- career/building-confidence.md
The update expands the lesson with practical confidence-building strategies, self-awareness tools, and actionable techniques to help participants develop lasting confidence in professional settings.
- **Confidence Definition & Characteristics**: Added clear definition of what confidence looks like in practice (poised, balanced, purposeful movement, ability to handle challenges)
- **Self-Awareness Section**: Integrated structured self-reflection questions to help identify strengths and growth areas
- **Confidence Barriers**: Added section on what can hurt confidence (taking on too much work, belittling leaders, perfectionism)
- **Practical Strategies**:
- Language pattern improvements (replacing weak filler words with stronger alternatives)
- Reframing negative self-talk techniques
- Daily …
> [Issue 2451] Enhance Existing Building Confidence Topic Outline

- career/interviewing/non-technical-interviewing.md
This PR enhances the non-technical interviewing curriculum by adding comprehensive content on interview question analysis, response strategies, and diversity/equity/inclusion topics. The update turns the existing outline into a complete educational framework that helps students understand what interviewers are really evaluating and how to respond effectively.
**Major Content Additions:**
- **Core Framework Addition**: Introduced the "Perfect Employee Framework" (Competent, Easy, Team Player, Stick Around) as the foundation for understanding all interview questions
- **17 Common Interview Questions**: Added detailed analysis of difficult questions including "What's your biggest weakness?", "How do you handle stress?", and goal-setting questions
- **DEI Interview Section**: New …
> [Issue 2450] Enhance Existing Non-Technical Interview Questions Topic Outline

- pair-programming/week-7/react-express-app/react-expressjs.md
- projects/weather-app.md
Add disclaimer note in the week 7 pair programming topic outline ([General Full-Stack Web App Using React and Express](https://github.com/Techtonica/curriculum/blob/main/pair-programming/week-7/react-express-app/react-expressjs.md)) and [the weather app project topic outline](https://github.com/Techtonica/curriculum/blob/main/projects/weather-app.md) about their respective relation to one another enabling participants to be able to build their weekly project independently.
Issue Number: #2327
Documentation update
> [Issue 2375] Add disclaimer in week-7 pair programming assignment

- javascript/advanced-javascript-resources.md
- node-js/advanced-nodejs.md
**Advanced NodeJS**
The lesson covers enterprise-level Node.js concepts including middleware patterns, authentication, API design, performance optimization, and production deployment with practical, job-relevant activities.
**Advanced JS**
The lesson covers closures, prototypes, and ES6+ features with a human-centered approach that acknowledges the unique challenges faced by career changers while building confidence through practical, hands-on learning.
**Advanced NodeJS**
- Developed complete 4-5 hour topic outline with structured time allocation
- Wrote career-focused motivation explaining transition from frontend/other fields to backend
- Established clear learning objectives covering production-ready Node.js development
- Designed 5 comprehensive activities simulating real workplace …
> [Issue 2477] Create Advanced NodeJS & Advanced JS Topic Outlines

- algorithms/bridges.md
Issue #2270 
- Topic outline with time estimates, prerequisites, and learning objectives
- 4 with step-by-step walkthroughs:
- Bridge concept understanding with visual analogies
- Weather API integration (first bridge building experience)
- Contact form with POST request handling
- Error handling and debugging tool
- Prerequisites section linking to existing curriculum
- Real-world analogies (restaurant orders, phone calls, physical bridges)
- Interactive code examples
- Beginner-friendly language
- Progressive learning
- Interactive code blocks
- Hands-on activities
> [Issue 2270] Create bridges.md

- javascript/javascript-maps-and-sets.md
This pull request addresses issue #2421 by updating the lesson material on JavaScript Maps and Sets. The desired end result was to add a detailed documentation on sets and organize the structure in a way that learners can prioritize the learning activities before going to view external sites.
- Added MDN docs link for Sets
- Renamed the MDN docs text for Maps
- Moved the materials section to additional resources at the bottom of the page
- Added a common pitfall section for Maps and Sets
- Issue Number: #2421 
- Topic Outline
- There should be primary docs for Sets.
- Prioritization of hands-on learning with the newly added activities.
> [Issue 2421] Update JS Map and Set lesson materials 

- pair-programming/week-4/hello-component/App.js
- pair-programming/week-4/hello-component/Hello.js
- pair-programming/week-4/hello-component/README.md
This pull request addresses the audit for the "Add your Name to a 'Hello' React Component" pair programming lesson (Issue #2459). The changes ensure that no completed solutions are present, instructions are clear for both pair and async learners, and the lesson is properly linked in the curriculum.
- Removed completed solution code from `hello-component/Hello.js`. Now only starter code is provided, with TODO comments for learners.
- Ensured `App.js` demonstrates usage of `Hello` with starter names.
- Updated `hello-component/README.md`:
- Clear pair programming instructions (driver/navigator)
- Added async (solo) instructions
- Hints, live demo, and expected output
- Linked the Hello exercise in `week-4/README.md` under Pair Programming Exercises section.
- Issue Number: #2459
1. Open …
> Audit Fix: Convert Hello React component to starter code, update Week 4 README (Issue #2459)

- pair-programming/week-1/first-div/script.js
- pair-programming/week-2/modify-dom/script.js
- pair-programming/week-2/newspaper-list/script.js
- pair-programming/week-3/form-validation/script.js
- pair-programming/week-3/media-and-forms/script.js
- pair-programming/week-3/media-and-forms/style.css
- pair-programming/week-3/toggle-button/script.js
- pair-programming/week-4/button-component/App.js
- pair-programming/week-4/mini-project-OOP/event.js
- pair-programming/week-5/fetch-api/index.js
- pair-programming/week-5/react-couter-app/App.js
- pair-programming/week-6/expressjs-router/index.js
- pair-programming/week-6/nodejs-weather-app/server.mjs
- pair-programming/week-7/Factorial_Calculation_Using_Recursion.js
- pair-programming/week-7/react-express-app/starter-code/React-express-starter-code/client/src/App.js
- pair-programming/week-7/react-forms/App.js
This pull request addresses an issue where several pair programming exercises from Week 1 to Week 7 contained completed solutions instead of the intended starter files or prompts. This change reverts the identified files back to their starter state to ensure the integrity of the curriculum for pair programming sessions.
The following files have been reverted from completed solutions to starter templates:
-   **Week 1:**
-   `week-1/first-div/script.js`: Replaced completed DOM manipulation logic with commented-out prompts.
-   **Week 2:**
-   `week-2/newspaper-list/script.js`: Removed the solution and left only the data array and a prompt.
-   `week-2/modify-dom/script.js`: Removed the solution and left the data array and commented-out prompts.
-   **Week 3:**
- …
> chore: delete complete pair programming exercises

- databases/install-postgres-with-docker.md
The instructions for the hands-on exercise creating a Postgres database inside a Docker container were updated for clarity and accuracy. 
*Details below.
1. Additional instruction to make sure Docker is open and running before next steps following installation.
2. Additional instruction on how exit window and input new command in terminal.
3. Additional information added for the case where user wants to reference current directory instead of Home.
4. Update instructions to use acceptable placeholder email after encountering error from PG Admin.
5. Clarifying instruction added to specifically point to which password is used to sign in to PG Admin.
6. Additional instruction on input for adding server in PG Admin following sign in.
*screenshots below.
Related to #2374 
- Bug fix
- …
> Docker Postgres Instructions Updated

- react-js/class-based-components/README.md
This README provides context about why class components are outdated, their historical usage, the transition to functional components, and why understanding them remains important for maintaining legacy codebases.
- **New Documentation**: Created detailed README.md explaining React class components context
- **Historical Context**: Added timeline of React's evolution from class to functional components
- **Code Examples**: Included before/after comparisons showing class vs functional component patterns
- **Migration Guidance**: Provided strategies for working with legacy codebases
- **Best Practices**: Outlined when to use each approach and migration strategies
New topic outline
1. **Content Review**: 
- Read through the entire README.md to ensure clarity and accuracy
- Verify that …
> [Issue 2372] React-Class-Components folder README.md

- pair-programming/week-4/hello-component/App.js
- pair-programming/week-4/hello-component/Hello.js
- pair-programming/week-4/hello-component/README.md
- pair-programming/week-4/hello-component/package.json
- pair-programming/week-4/hello-component/public/index.html
- pair-programming/week-4/hello-component/src/App.js
- pair-programming/week-4/hello-component/src/index.js
- pair-programming/week-4/hello-component/src/styles.css
This is a second iteration of an already addressed issue. The existing folder for the hello component exercise does not contain the full react architecture. 
Changes have changed from this architecture
```
|
|_README.md
|_App.js
|_Hello.js
```
to this architecture
```
|
|_package.json
|_README.md
|_src
|_App.js
|_index.js
|_styles.css
|_public
|_index.html
```
Note that the `hello.js` file has been removed because the learner should be creating this.
> Audit Hello Component Exercise

- objectives/11.md
- objectives/7.md
- objectives/week-6-assessment.md
- pair-programming/week-1/Divs_and_DOM_Manipulation/README.md
> docs: fix typos

- personal-brand/personal-branding.md
Address [Feedback](https://github.com/Techtonica/curriculum/pull/2344#pullrequestreview-3138432161)
- Remove hashnote and keep dev.to reference
- Replaced URLs that no longer provide relevant content or lead to 404s
- Add authentic commenting quote from @MaggieFerro
- Add note about GH green tiles for personal website
- Generalize writing platform usecase comment
- Add dev.to and medium to pre-reqs
- Add TikTok section
- Clarify Twitter / X as an older platform with movement to Mastadon
- Clarify Mastadon usecase comment
- Leave comment for future "importance of social media presence" statement
- Employer reference authenticity statement
- Replace "or" with "and"
@MaggieFero I would love your help with [the TO-DO on L53](https://github.com/Techtonica/curriculum/pull/2515/files#diff-71a38d7 …
> Personal Branding Topic Outline Iteration
